// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/clearinghouse/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryPositionHealthRequest is the request for PositionHealth query
type QueryPositionHealthRequest struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPositionHealthRequest) Reset()         { *m = QueryPositionHealthRequest{} }
func (m *QueryPositionHealthRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPositionHealthRequest) ProtoMessage()    {}
func (*QueryPositionHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{0}
}
func (m *QueryPositionHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPositionHealthRequest.Unmarshal(m, b)
}
func (m *QueryPositionHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPositionHealthRequest.Marshal(b, m, deterministic)
}
func (m *QueryPositionHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPositionHealthRequest.Merge(m, src)
}
func (m *QueryPositionHealthRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPositionHealthRequest.Size(m)
}
func (m *QueryPositionHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPositionHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPositionHealthRequest proto.InternalMessageInfo

func (m *QueryPositionHealthRequest) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *QueryPositionHealthRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// QueryPositionHealthResponse is the response for PositionHealth query
type QueryPositionHealthResponse struct {
	Health               *PositionHealth `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryPositionHealthResponse) Reset()         { *m = QueryPositionHealthResponse{} }
func (m *QueryPositionHealthResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPositionHealthResponse) ProtoMessage()    {}
func (*QueryPositionHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{1}
}
func (m *QueryPositionHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPositionHealthResponse.Unmarshal(m, b)
}
func (m *QueryPositionHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPositionHealthResponse.Marshal(b, m, deterministic)
}
func (m *QueryPositionHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPositionHealthResponse.Merge(m, src)
}
func (m *QueryPositionHealthResponse) XXX_Size() int {
	return xxx_messageInfo_QueryPositionHealthResponse.Size(m)
}
func (m *QueryPositionHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPositionHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPositionHealthResponse proto.InternalMessageInfo

func (m *QueryPositionHealthResponse) GetHealth() *PositionHealth {
	if m != nil {
		return m.Health
	}
	return nil
}

// QueryAllPositionsHealthRequest is the request for AllPositionsHealth query
type QueryAllPositionsHealthRequest struct {
	OnlyUnhealthy        bool     `protobuf:"varint,1,opt,name=only_unhealthy,json=onlyUnhealthy,proto3" json:"only_unhealthy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAllPositionsHealthRequest) Reset()         { *m = QueryAllPositionsHealthRequest{} }
func (m *QueryAllPositionsHealthRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPositionsHealthRequest) ProtoMessage()    {}
func (*QueryAllPositionsHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{2}
}
func (m *QueryAllPositionsHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAllPositionsHealthRequest.Unmarshal(m, b)
}
func (m *QueryAllPositionsHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAllPositionsHealthRequest.Marshal(b, m, deterministic)
}
func (m *QueryAllPositionsHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPositionsHealthRequest.Merge(m, src)
}
func (m *QueryAllPositionsHealthRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAllPositionsHealthRequest.Size(m)
}
func (m *QueryAllPositionsHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPositionsHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPositionsHealthRequest proto.InternalMessageInfo

func (m *QueryAllPositionsHealthRequest) GetOnlyUnhealthy() bool {
	if m != nil {
		return m.OnlyUnhealthy
	}
	return false
}

// QueryAllPositionsHealthResponse is the response for AllPositionsHealth query
type QueryAllPositionsHealthResponse struct {
	Positions            []*PositionHealth `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryAllPositionsHealthResponse) Reset()         { *m = QueryAllPositionsHealthResponse{} }
func (m *QueryAllPositionsHealthResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPositionsHealthResponse) ProtoMessage()    {}
func (*QueryAllPositionsHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{3}
}
func (m *QueryAllPositionsHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAllPositionsHealthResponse.Unmarshal(m, b)
}
func (m *QueryAllPositionsHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAllPositionsHealthResponse.Marshal(b, m, deterministic)
}
func (m *QueryAllPositionsHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPositionsHealthResponse.Merge(m, src)
}
func (m *QueryAllPositionsHealthResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAllPositionsHealthResponse.Size(m)
}
func (m *QueryAllPositionsHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPositionsHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPositionsHealthResponse proto.InternalMessageInfo

func (m *QueryAllPositionsHealthResponse) GetPositions() []*PositionHealth {
	if m != nil {
		return m.Positions
	}
	return nil
}

// QueryLiquidationsRequest is the request for Liquidations query
type QueryLiquidationsRequest struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryLiquidationsRequest) Reset()         { *m = QueryLiquidationsRequest{} }
func (m *QueryLiquidationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidationsRequest) ProtoMessage()    {}
func (*QueryLiquidationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{4}
}
func (m *QueryLiquidationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLiquidationsRequest.Unmarshal(m, b)
}
func (m *QueryLiquidationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLiquidationsRequest.Marshal(b, m, deterministic)
}
func (m *QueryLiquidationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidationsRequest.Merge(m, src)
}
func (m *QueryLiquidationsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryLiquidationsRequest.Size(m)
}
func (m *QueryLiquidationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidationsRequest proto.InternalMessageInfo

func (m *QueryLiquidationsRequest) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *QueryLiquidationsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// QueryLiquidationsResponse is the response for Liquidations query
type QueryLiquidationsResponse struct {
	Liquidations         []*Liquidation `protobuf:"bytes,1,rep,name=liquidations,proto3" json:"liquidations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryLiquidationsResponse) Reset()         { *m = QueryLiquidationsResponse{} }
func (m *QueryLiquidationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLiquidationsResponse) ProtoMessage()    {}
func (*QueryLiquidationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{5}
}
func (m *QueryLiquidationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryLiquidationsResponse.Unmarshal(m, b)
}
func (m *QueryLiquidationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryLiquidationsResponse.Marshal(b, m, deterministic)
}
func (m *QueryLiquidationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLiquidationsResponse.Merge(m, src)
}
func (m *QueryLiquidationsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryLiquidationsResponse.Size(m)
}
func (m *QueryLiquidationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLiquidationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLiquidationsResponse proto.InternalMessageInfo

func (m *QueryLiquidationsResponse) GetLiquidations() []*Liquidation {
	if m != nil {
		return m.Liquidations
	}
	return nil
}

// QueryAtRiskPositionsRequest is the request for AtRiskPositions query
type QueryAtRiskPositionsRequest struct {
	Threshold            string   `protobuf:"bytes,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAtRiskPositionsRequest) Reset()         { *m = QueryAtRiskPositionsRequest{} }
func (m *QueryAtRiskPositionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAtRiskPositionsRequest) ProtoMessage()    {}
func (*QueryAtRiskPositionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{6}
}
func (m *QueryAtRiskPositionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAtRiskPositionsRequest.Unmarshal(m, b)
}
func (m *QueryAtRiskPositionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAtRiskPositionsRequest.Marshal(b, m, deterministic)
}
func (m *QueryAtRiskPositionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAtRiskPositionsRequest.Merge(m, src)
}
func (m *QueryAtRiskPositionsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAtRiskPositionsRequest.Size(m)
}
func (m *QueryAtRiskPositionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAtRiskPositionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAtRiskPositionsRequest proto.InternalMessageInfo

func (m *QueryAtRiskPositionsRequest) GetThreshold() string {
	if m != nil {
		return m.Threshold
	}
	return ""
}

// QueryAtRiskPositionsResponse is the response for AtRiskPositions query
type QueryAtRiskPositionsResponse struct {
	Positions            []*PositionHealth `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryAtRiskPositionsResponse) Reset()         { *m = QueryAtRiskPositionsResponse{} }
func (m *QueryAtRiskPositionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAtRiskPositionsResponse) ProtoMessage()    {}
func (*QueryAtRiskPositionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8323d9ec3e0614a3, []int{7}
}
func (m *QueryAtRiskPositionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAtRiskPositionsResponse.Unmarshal(m, b)
}
func (m *QueryAtRiskPositionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAtRiskPositionsResponse.Marshal(b, m, deterministic)
}
func (m *QueryAtRiskPositionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAtRiskPositionsResponse.Merge(m, src)
}
func (m *QueryAtRiskPositionsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAtRiskPositionsResponse.Size(m)
}
func (m *QueryAtRiskPositionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAtRiskPositionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAtRiskPositionsResponse proto.InternalMessageInfo

func (m *QueryAtRiskPositionsResponse) GetPositions() []*PositionHealth {
	if m != nil {
		return m.Positions
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryPositionHealthRequest)(nil), "perpdex.clearinghouse.v1.QueryPositionHealthRequest")
	proto.RegisterType((*QueryPositionHealthResponse)(nil), "perpdex.clearinghouse.v1.QueryPositionHealthResponse")
	proto.RegisterType((*QueryAllPositionsHealthRequest)(nil), "perpdex.clearinghouse.v1.QueryAllPositionsHealthRequest")
	proto.RegisterType((*QueryAllPositionsHealthResponse)(nil), "perpdex.clearinghouse.v1.QueryAllPositionsHealthResponse")
	proto.RegisterType((*QueryLiquidationsRequest)(nil), "perpdex.clearinghouse.v1.QueryLiquidationsRequest")
	proto.RegisterType((*QueryLiquidationsResponse)(nil), "perpdex.clearinghouse.v1.QueryLiquidationsResponse")
	proto.RegisterType((*QueryAtRiskPositionsRequest)(nil), "perpdex.clearinghouse.v1.QueryAtRiskPositionsRequest")
	proto.RegisterType((*QueryAtRiskPositionsResponse)(nil), "perpdex.clearinghouse.v1.QueryAtRiskPositionsResponse")
}

func init() {
	proto.RegisterFile("perpdex/clearinghouse/v1/query.proto", fileDescriptor_8323d9ec3e0614a3)
}

var fileDescriptor_8323d9ec3e0614a3 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xd6, 0x16, 0x25, 0x6a, 0x86, 0xb6, 0x48, 0x16, 0x42, 0xcb, 0x36, 0x82, 0x60, 0x28, 0x0a,
	0x87, 0xee, 0xaa, 0x09, 0xe1, 0x47, 0x08, 0x89, 0x72, 0x80, 0x56, 0xe2, 0x40, 0x57, 0xe2, 0xc2,
	0x25, 0x72, 0xbb, 0x6e, 0xd6, 0x8a, 0xb3, 0xde, 0xac, 0xbd, 0x15, 0x51, 0xd5, 0x0b, 0xaf, 0xc0,
	0x43, 0x70, 0xe0, 0xc8, 0x95, 0xb7, 0x80, 0x47, 0xe0, 0x41, 0x50, 0xbc, 0x4e, 0x9b, 0x84, 0xb5,
	0x56, 0x41, 0x1c, 0x3d, 0x9e, 0xef, 0x9b, 0x6f, 0x66, 0x3e, 0x1b, 0x1e, 0xa4, 0x34, 0x4b, 0x23,
	0xfa, 0x29, 0x38, 0xe1, 0x94, 0x64, 0x2c, 0x19, 0xc4, 0x22, 0x97, 0x34, 0x38, 0xdb, 0x0b, 0xc6,
	0x39, 0xcd, 0x26, 0x7e, 0x9a, 0x09, 0x25, 0x90, 0x6b, 0xb2, 0xfc, 0x85, 0x2c, 0xff, 0x6c, 0xcf,
	0x6b, 0x0e, 0x84, 0x18, 0x70, 0x1a, 0x90, 0x94, 0x05, 0x24, 0x49, 0x84, 0x22, 0x8a, 0x89, 0x44,
	0x16, 0x38, 0xcf, 0xce, 0xae, 0x26, 0x29, 0x35, 0x59, 0xf8, 0x08, 0xbc, 0xa3, 0x69, 0xb1, 0xf7,
	0x42, 0xb2, 0x29, 0xfa, 0x80, 0x12, 0xae, 0xe2, 0x90, 0x8e, 0x73, 0x2a, 0x15, 0xba, 0x05, 0x75,
	0x95, 0x91, 0x88, 0x66, 0xae, 0xd3, 0x72, 0xda, 0x8d, 0xd0, 0x9c, 0xd0, 0x36, 0x34, 0x46, 0x24,
	0x1b, 0x52, 0xd5, 0x67, 0x91, 0xbb, 0xa6, 0xaf, 0xd6, 0x8b, 0xc0, 0x61, 0x84, 0xfb, 0xb0, 0x5d,
	0x4a, 0x29, 0x53, 0x91, 0x48, 0x8a, 0x5e, 0x41, 0x3d, 0xd6, 0x11, 0xcd, 0x79, 0xbd, 0xd3, 0xf6,
	0x6d, 0x0d, 0xfa, 0x4b, 0x0c, 0x06, 0x87, 0xdf, 0xc2, 0x1d, 0x5d, 0x60, 0x9f, 0xf3, 0x59, 0x86,
	0x5c, 0xd4, 0xbd, 0x03, 0x5b, 0x22, 0xe1, 0x93, 0x7e, 0x9e, 0x14, 0x90, 0x89, 0xae, 0xb5, 0x1e,
	0x6e, 0x4e, 0xa3, 0x1f, 0x66, 0x41, 0xcc, 0xe0, 0xae, 0x95, 0xc8, 0xa8, 0x7d, 0x03, 0x8d, 0x74,
	0x76, 0xe5, 0x3a, 0xad, 0x6b, 0x2b, 0x09, 0xbe, 0x82, 0xe2, 0x03, 0x70, 0x75, 0xa9, 0x77, 0x6c,
	0x9c, 0xb3, 0xa8, 0x58, 0x54, 0xd5, 0x94, 0x6f, 0x42, 0x8d, 0xb3, 0x11, 0x53, 0x7a, 0xc2, 0x9b,
	0x61, 0x71, 0xc0, 0xa7, 0x70, 0xbb, 0x84, 0xc9, 0xc8, 0x3d, 0x84, 0x0d, 0x3e, 0x17, 0x37, 0x8a,
	0x77, 0xec, 0x8a, 0xe7, 0x58, 0xc2, 0x05, 0x28, 0x7e, 0x61, 0xd6, 0xb8, 0xaf, 0x42, 0x26, 0x87,
	0x97, 0xf3, 0x99, 0x89, 0x6e, 0x42, 0x43, 0xc5, 0x19, 0x95, 0xb1, 0xe0, 0x91, 0xd1, 0x7d, 0x15,
	0xc0, 0xa7, 0xd0, 0x2c, 0x07, 0xff, 0xdf, 0xb1, 0x76, 0x7e, 0xd5, 0xa0, 0xa6, 0x0b, 0xa1, 0x1f,
	0x0e, 0x6c, 0x2d, 0xe6, 0xa1, 0xc7, 0x76, 0x46, 0xbb, 0xe7, 0xbd, 0xde, 0x8a, 0xa8, 0xa2, 0x23,
	0xfc, 0xf2, 0xf3, 0xcf, 0xdf, 0x5f, 0xd6, 0x9e, 0xa2, 0x5e, 0x60, 0x7d, 0x77, 0x85, 0xed, 0x82,
	0xf3, 0x62, 0xbd, 0x17, 0xc1, 0xf9, 0xe5, 0x1b, 0xba, 0x40, 0xdf, 0x1d, 0x40, 0x7f, 0xdb, 0x10,
	0x3d, 0xab, 0x10, 0x63, 0x7d, 0x02, 0xde, 0xf3, 0x7f, 0x40, 0x9a, 0x56, 0xda, 0xba, 0x15, 0x8c,
	0x5a, 0x55, 0xad, 0xa0, 0xaf, 0x0e, 0x6c, 0xcc, 0xfb, 0x10, 0x75, 0x2a, 0xaa, 0x96, 0xd8, 0xdf,
	0xeb, 0xae, 0x84, 0x31, 0x1a, 0x7d, 0xad, 0xb1, 0x8d, 0x1e, 0xda, 0x35, 0xce, 0xbb, 0x19, 0x7d,
	0x73, 0xe0, 0xc6, 0x92, 0x19, 0x51, 0xd5, 0xa6, 0xcb, 0x9d, 0xef, 0x3d, 0x59, 0x15, 0x66, 0x24,
	0x3f, 0xd2, 0x92, 0xef, 0xa3, 0x7b, 0x76, 0xc9, 0x44, 0xed, 0x66, 0x4c, 0x0e, 0x5f, 0xf7, 0x3e,
	0x76, 0x07, 0x4c, 0xc5, 0xf9, 0xb1, 0x7f, 0x22, 0x46, 0x81, 0x48, 0x69, 0x42, 0x78, 0x1a, 0x13,
	0x0d, 0xdc, 0x9d, 0x22, 0x97, 0xb1, 0xfa, 0x4b, 0x3f, 0xae, 0xeb, 0x3f, 0xbd, 0xfb, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x0a, 0x55, 0x3d, 0xeb, 0x59, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// PositionHealth returns the health status of a position
	PositionHealth(ctx context.Context, in *QueryPositionHealthRequest, opts ...grpc.CallOption) (*QueryPositionHealthResponse, error)
	// AllPositionsHealth returns health status of all positions
	AllPositionsHealth(ctx context.Context, in *QueryAllPositionsHealthRequest, opts ...grpc.CallOption) (*QueryAllPositionsHealthResponse, error)
	// Liquidations returns liquidation history
	Liquidations(ctx context.Context, in *QueryLiquidationsRequest, opts ...grpc.CallOption) (*QueryLiquidationsResponse, error)
	// AtRiskPositions returns positions close to liquidation
	AtRiskPositions(ctx context.Context, in *QueryAtRiskPositionsRequest, opts ...grpc.CallOption) (*QueryAtRiskPositionsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PositionHealth(ctx context.Context, in *QueryPositionHealthRequest, opts ...grpc.CallOption) (*QueryPositionHealthResponse, error) {
	out := new(QueryPositionHealthResponse)
	err := c.cc.Invoke(ctx, "/perpdex.clearinghouse.v1.Query/PositionHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllPositionsHealth(ctx context.Context, in *QueryAllPositionsHealthRequest, opts ...grpc.CallOption) (*QueryAllPositionsHealthResponse, error) {
	out := new(QueryAllPositionsHealthResponse)
	err := c.cc.Invoke(ctx, "/perpdex.clearinghouse.v1.Query/AllPositionsHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Liquidations(ctx context.Context, in *QueryLiquidationsRequest, opts ...grpc.CallOption) (*QueryLiquidationsResponse, error) {
	out := new(QueryLiquidationsResponse)
	err := c.cc.Invoke(ctx, "/perpdex.clearinghouse.v1.Query/Liquidations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AtRiskPositions(ctx context.Context, in *QueryAtRiskPositionsRequest, opts ...grpc.CallOption) (*QueryAtRiskPositionsResponse, error) {
	out := new(QueryAtRiskPositionsResponse)
	err := c.cc.Invoke(ctx, "/perpdex.clearinghouse.v1.Query/AtRiskPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// PositionHealth returns the health status of a position
	PositionHealth(context.Context, *QueryPositionHealthRequest) (*QueryPositionHealthResponse, error)
	// AllPositionsHealth returns health status of all positions
	AllPositionsHealth(context.Context, *QueryAllPositionsHealthRequest) (*QueryAllPositionsHealthResponse, error)
	// Liquidations returns liquidation history
	Liquidations(context.Context, *QueryLiquidationsRequest) (*QueryLiquidationsResponse, error)
	// AtRiskPositions returns positions close to liquidation
	AtRiskPositions(context.Context, *QueryAtRiskPositionsRequest) (*QueryAtRiskPositionsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PositionHealth(ctx context.Context, req *QueryPositionHealthRequest) (*QueryPositionHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PositionHealth not implemented")
}
func (*UnimplementedQueryServer) AllPositionsHealth(ctx context.Context, req *QueryAllPositionsHealthRequest) (*QueryAllPositionsHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllPositionsHealth not implemented")
}
func (*UnimplementedQueryServer) Liquidations(ctx context.Context, req *QueryLiquidationsRequest) (*QueryLiquidationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Liquidations not implemented")
}
func (*UnimplementedQueryServer) AtRiskPositions(ctx context.Context, req *QueryAtRiskPositionsRequest) (*QueryAtRiskPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AtRiskPositions not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PositionHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPositionHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PositionHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.clearinghouse.v1.Query/PositionHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PositionHealth(ctx, req.(*QueryPositionHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllPositionsHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPositionsHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllPositionsHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.clearinghouse.v1.Query/AllPositionsHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllPositionsHealth(ctx, req.(*QueryAllPositionsHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Liquidations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLiquidationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Liquidations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.clearinghouse.v1.Query/Liquidations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Liquidations(ctx, req.(*QueryLiquidationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AtRiskPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAtRiskPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AtRiskPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.clearinghouse.v1.Query/AtRiskPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AtRiskPositions(ctx, req.(*QueryAtRiskPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.clearinghouse.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PositionHealth",
			Handler:    _Query_PositionHealth_Handler,
		},
		{
			MethodName: "AllPositionsHealth",
			Handler:    _Query_AllPositionsHealth_Handler,
		},
		{
			MethodName: "Liquidations",
			Handler:    _Query_Liquidations_Handler,
		},
		{
			MethodName: "AtRiskPositions",
			Handler:    _Query_AtRiskPositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/clearinghouse/v1/query.proto",
}
