// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/clearinghouse/v1/tx.proto

package types

import (
	context "context"
	_ "cosmossdk.io/api/cosmos/msg/v1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgLiquidate defines the Liquidate request
type MsgLiquidate struct {
	Liquidator           string   `protobuf:"bytes,1,opt,name=liquidator,proto3" json:"liquidator,omitempty"`
	Trader               string   `protobuf:"bytes,2,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string   `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLiquidate) Reset()         { *m = MsgLiquidate{} }
func (m *MsgLiquidate) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidate) ProtoMessage()    {}
func (*MsgLiquidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f572d49482ba274, []int{0}
}
func (m *MsgLiquidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLiquidate.Unmarshal(m, b)
}
func (m *MsgLiquidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLiquidate.Marshal(b, m, deterministic)
}
func (m *MsgLiquidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidate.Merge(m, src)
}
func (m *MsgLiquidate) XXX_Size() int {
	return xxx_messageInfo_MsgLiquidate.Size(m)
}
func (m *MsgLiquidate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidate proto.InternalMessageInfo

func (m *MsgLiquidate) GetLiquidator() string {
	if m != nil {
		return m.Liquidator
	}
	return ""
}

func (m *MsgLiquidate) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *MsgLiquidate) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// MsgLiquidateResponse defines the Liquidate response
type MsgLiquidateResponse struct {
	LiquidationId        string   `protobuf:"bytes,1,opt,name=liquidation_id,json=liquidationId,proto3" json:"liquidation_id,omitempty"`
	LiquidatedSize       string   `protobuf:"bytes,2,opt,name=liquidated_size,json=liquidatedSize,proto3" json:"liquidated_size,omitempty"`
	LiquidationPrice     string   `protobuf:"bytes,3,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	PenaltyPaid          string   `protobuf:"bytes,4,opt,name=penalty_paid,json=penaltyPaid,proto3" json:"penalty_paid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLiquidateResponse) Reset()         { *m = MsgLiquidateResponse{} }
func (m *MsgLiquidateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidateResponse) ProtoMessage()    {}
func (*MsgLiquidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f572d49482ba274, []int{1}
}
func (m *MsgLiquidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLiquidateResponse.Unmarshal(m, b)
}
func (m *MsgLiquidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLiquidateResponse.Marshal(b, m, deterministic)
}
func (m *MsgLiquidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidateResponse.Merge(m, src)
}
func (m *MsgLiquidateResponse) XXX_Size() int {
	return xxx_messageInfo_MsgLiquidateResponse.Size(m)
}
func (m *MsgLiquidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidateResponse proto.InternalMessageInfo

func (m *MsgLiquidateResponse) GetLiquidationId() string {
	if m != nil {
		return m.LiquidationId
	}
	return ""
}

func (m *MsgLiquidateResponse) GetLiquidatedSize() string {
	if m != nil {
		return m.LiquidatedSize
	}
	return ""
}

func (m *MsgLiquidateResponse) GetLiquidationPrice() string {
	if m != nil {
		return m.LiquidationPrice
	}
	return ""
}

func (m *MsgLiquidateResponse) GetPenaltyPaid() string {
	if m != nil {
		return m.PenaltyPaid
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgLiquidate)(nil), "perpdex.clearinghouse.v1.MsgLiquidate")
	proto.RegisterType((*MsgLiquidateResponse)(nil), "perpdex.clearinghouse.v1.MsgLiquidateResponse")
}

func init() { proto.RegisterFile("perpdex/clearinghouse/v1/tx.proto", fileDescriptor_3f572d49482ba274) }

var fileDescriptor_3f572d49482ba274 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0xae, 0xd2, 0x40,
	0x14, 0xc6, 0x53, 0x51, 0x22, 0x23, 0xa2, 0x4c, 0x88, 0xd6, 0xba, 0x11, 0x12, 0xff, 0x04, 0x43,
	0x27, 0x48, 0x34, 0xc6, 0x9d, 0xec, 0x48, 0x24, 0x21, 0x65, 0xe7, 0xa6, 0x19, 0x3a, 0x27, 0x65,
	0x22, 0xed, 0x0c, 0x33, 0x03, 0x01, 0x56, 0xc6, 0xa5, 0x4f, 0xc3, 0x42, 0x7d, 0x10, 0x5f, 0x82,
	0xd7, 0x30, 0x6d, 0x87, 0x30, 0xde, 0xdc, 0x9b, 0xdc, 0x4d, 0x93, 0xf3, 0x3b, 0xdf, 0xf9, 0x7a,
	0xce, 0xd7, 0xa2, 0xae, 0x04, 0x25, 0x19, 0xec, 0x48, 0xb2, 0x02, 0xaa, 0x78, 0x9e, 0x2e, 0xc5,
	0x46, 0x03, 0xd9, 0x0e, 0x89, 0xd9, 0x85, 0x52, 0x09, 0x23, 0xb0, 0x6f, 0x25, 0xe1, 0x7f, 0x92,
	0x70, 0x3b, 0x0c, 0x9e, 0x26, 0x42, 0x67, 0x42, 0x93, 0x4c, 0xa7, 0xc5, 0x44, 0xa6, 0xd3, 0x6a,
	0x24, 0x78, 0x56, 0x35, 0xe2, 0xb2, 0x22, 0x55, 0x61, 0x5b, 0x6d, 0x9a, 0xf1, 0x5c, 0x90, 0xf2,
	0x59, 0xa1, 0xde, 0x6f, 0x0f, 0x35, 0xa7, 0x3a, 0xfd, 0xc2, 0xd7, 0x1b, 0xce, 0xa8, 0x01, 0xfc,
	0x11, 0xa1, 0x95, 0x2d, 0x84, 0xf2, 0xbd, 0x17, 0xde, 0x9b, 0xc6, 0xd8, 0xff, 0xfb, 0x6b, 0xd0,
	0xb1, 0x4e, 0x9f, 0x19, 0x53, 0xa0, 0xf5, 0xdc, 0x14, 0xdb, 0x44, 0x8e, 0x16, 0x3f, 0x41, 0x75,
	0xa3, 0x28, 0x03, 0xe5, 0xdf, 0x29, 0xa6, 0x22, 0x5b, 0xe1, 0xe7, 0xa8, 0x91, 0x51, 0xf5, 0x0d,
	0x4c, 0xcc, 0x99, 0x5f, 0x2b, 0x5b, 0xf7, 0x2b, 0x30, 0x61, 0x9f, 0x3e, 0xfc, 0x38, 0x1d, 0xfb,
	0x8e, 0xcb, 0xcf, 0xd3, 0xb1, 0xdf, 0xbb, 0x3e, 0x17, 0x77, 0xcd, 0xde, 0x1f, 0x0f, 0x75, 0x5c,
	0x10, 0x81, 0x96, 0x22, 0xd7, 0x80, 0x5f, 0xa2, 0xd6, 0xd9, 0x8d, 0x8b, 0xbc, 0x78, 0x65, 0x79,
	0x43, 0xf4, 0xd0, 0xa1, 0x13, 0x86, 0x5f, 0xa3, 0x47, 0x67, 0x00, 0x2c, 0xd6, 0xfc, 0x00, 0x76,
	0xeb, 0xd6, 0x05, 0xcf, 0xf9, 0x01, 0xf0, 0x5b, 0xd4, 0x76, 0xfd, 0xa4, 0xe2, 0x09, 0xd8, 0x2b,
	0x1e, 0x3b, 0x8d, 0x59, 0xc1, 0x71, 0x17, 0x35, 0x25, 0xe4, 0x74, 0x65, 0xf6, 0xb1, 0xa4, 0x9c,
	0xf9, 0x77, 0x4b, 0xdd, 0x03, 0xcb, 0x66, 0x94, 0xb3, 0x77, 0x6b, 0x54, 0x9b, 0xea, 0x14, 0x27,
	0xa8, 0x71, 0xc9, 0xfc, 0x55, 0x78, 0xd3, 0x67, 0x0e, 0xdd, 0x1b, 0x83, 0xf0, 0x76, 0xba, 0x73,
	0x16, 0xc1, 0xbd, 0xef, 0xa7, 0x63, 0xdf, 0x1b, 0xbf, 0xff, 0x3a, 0x4a, 0xb9, 0x59, 0x6e, 0x16,
	0x61, 0x22, 0x32, 0x22, 0xca, 0x6d, 0xe4, 0x92, 0x92, 0xc2, 0x6c, 0x50, 0xe4, 0x7c, 0x35, 0x69,
	0xb3, 0x97, 0xa0, 0x17, 0xf5, 0xf2, 0x0f, 0x19, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xed,
	0x48, 0x74, 0xa7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Liquidate triggers liquidation of an unhealthy position
	Liquidate(ctx context.Context, in *MsgLiquidate, opts ...grpc.CallOption) (*MsgLiquidateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Liquidate(ctx context.Context, in *MsgLiquidate, opts ...grpc.CallOption) (*MsgLiquidateResponse, error) {
	out := new(MsgLiquidateResponse)
	err := c.cc.Invoke(ctx, "/perpdex.clearinghouse.v1.Msg/Liquidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Liquidate triggers liquidation of an unhealthy position
	Liquidate(context.Context, *MsgLiquidate) (*MsgLiquidateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Liquidate(ctx context.Context, req *MsgLiquidate) (*MsgLiquidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Liquidate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Liquidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLiquidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Liquidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.clearinghouse.v1.Msg/Liquidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Liquidate(ctx, req.(*MsgLiquidate))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.clearinghouse.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Liquidate",
			Handler:    _Msg_Liquidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/clearinghouse/v1/tx.proto",
}
