// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/clearinghouse/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LiquidationStatus represents the status of a liquidation
type LiquidationStatus int32

const (
	LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED LiquidationStatus = 0
	LiquidationStatus_LIQUIDATION_STATUS_PENDING     LiquidationStatus = 1
	LiquidationStatus_LIQUIDATION_STATUS_EXECUTED    LiquidationStatus = 2
	LiquidationStatus_LIQUIDATION_STATUS_FAILED      LiquidationStatus = 3
)

var LiquidationStatus_name = map[int32]string{
	0: "LIQUIDATION_STATUS_UNSPECIFIED",
	1: "LIQUIDATION_STATUS_PENDING",
	2: "LIQUIDATION_STATUS_EXECUTED",
	3: "LIQUIDATION_STATUS_FAILED",
}

var LiquidationStatus_value = map[string]int32{
	"LIQUIDATION_STATUS_UNSPECIFIED": 0,
	"LIQUIDATION_STATUS_PENDING":     1,
	"LIQUIDATION_STATUS_EXECUTED":    2,
	"LIQUIDATION_STATUS_FAILED":      3,
}

func (x LiquidationStatus) String() string {
	return proto.EnumName(LiquidationStatus_name, int32(x))
}

func (LiquidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2fc35641f20b2178, []int{0}
}

// Liquidation represents a liquidation event
type Liquidation struct {
	LiquidationId        string            `protobuf:"bytes,1,opt,name=liquidation_id,json=liquidationId,proto3" json:"liquidation_id,omitempty"`
	Trader               string            `protobuf:"bytes,2,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string            `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	PositionSize         string            `protobuf:"bytes,4,opt,name=position_size,json=positionSize,proto3" json:"position_size,omitempty"`
	EntryPrice           string            `protobuf:"bytes,5,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarkPrice            string            `protobuf:"bytes,6,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	LiquidationPrice     string            `protobuf:"bytes,7,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	MarginDeficit        string            `protobuf:"bytes,8,opt,name=margin_deficit,json=marginDeficit,proto3" json:"margin_deficit,omitempty"`
	Penalty              string            `protobuf:"bytes,9,opt,name=penalty,proto3" json:"penalty,omitempty"`
	Status               LiquidationStatus `protobuf:"varint,10,opt,name=status,proto3,enum=perpdex.clearinghouse.v1.LiquidationStatus" json:"status,omitempty"`
	Timestamp            int64             `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Liquidation) Reset()         { *m = Liquidation{} }
func (m *Liquidation) String() string { return proto.CompactTextString(m) }
func (*Liquidation) ProtoMessage()    {}
func (*Liquidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fc35641f20b2178, []int{0}
}
func (m *Liquidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Liquidation.Unmarshal(m, b)
}
func (m *Liquidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Liquidation.Marshal(b, m, deterministic)
}
func (m *Liquidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Liquidation.Merge(m, src)
}
func (m *Liquidation) XXX_Size() int {
	return xxx_messageInfo_Liquidation.Size(m)
}
func (m *Liquidation) XXX_DiscardUnknown() {
	xxx_messageInfo_Liquidation.DiscardUnknown(m)
}

var xxx_messageInfo_Liquidation proto.InternalMessageInfo

func (m *Liquidation) GetLiquidationId() string {
	if m != nil {
		return m.LiquidationId
	}
	return ""
}

func (m *Liquidation) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Liquidation) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *Liquidation) GetPositionSize() string {
	if m != nil {
		return m.PositionSize
	}
	return ""
}

func (m *Liquidation) GetEntryPrice() string {
	if m != nil {
		return m.EntryPrice
	}
	return ""
}

func (m *Liquidation) GetMarkPrice() string {
	if m != nil {
		return m.MarkPrice
	}
	return ""
}

func (m *Liquidation) GetLiquidationPrice() string {
	if m != nil {
		return m.LiquidationPrice
	}
	return ""
}

func (m *Liquidation) GetMarginDeficit() string {
	if m != nil {
		return m.MarginDeficit
	}
	return ""
}

func (m *Liquidation) GetPenalty() string {
	if m != nil {
		return m.Penalty
	}
	return ""
}

func (m *Liquidation) GetStatus() LiquidationStatus {
	if m != nil {
		return m.Status
	}
	return LiquidationStatus_LIQUIDATION_STATUS_UNSPECIFIED
}

func (m *Liquidation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// PositionHealth represents the health status of a position
type PositionHealth struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	MarginRatio          string   `protobuf:"bytes,3,opt,name=margin_ratio,json=marginRatio,proto3" json:"margin_ratio,omitempty"`
	MaintenanceMargin    string   `protobuf:"bytes,4,opt,name=maintenance_margin,json=maintenanceMargin,proto3" json:"maintenance_margin,omitempty"`
	AccountEquity        string   `protobuf:"bytes,5,opt,name=account_equity,json=accountEquity,proto3" json:"account_equity,omitempty"`
	IsHealthy            bool     `protobuf:"varint,6,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	AtRisk               bool     `protobuf:"varint,7,opt,name=at_risk,json=atRisk,proto3" json:"at_risk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionHealth) Reset()         { *m = PositionHealth{} }
func (m *PositionHealth) String() string { return proto.CompactTextString(m) }
func (*PositionHealth) ProtoMessage()    {}
func (*PositionHealth) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fc35641f20b2178, []int{1}
}
func (m *PositionHealth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionHealth.Unmarshal(m, b)
}
func (m *PositionHealth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionHealth.Marshal(b, m, deterministic)
}
func (m *PositionHealth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionHealth.Merge(m, src)
}
func (m *PositionHealth) XXX_Size() int {
	return xxx_messageInfo_PositionHealth.Size(m)
}
func (m *PositionHealth) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionHealth.DiscardUnknown(m)
}

var xxx_messageInfo_PositionHealth proto.InternalMessageInfo

func (m *PositionHealth) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *PositionHealth) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *PositionHealth) GetMarginRatio() string {
	if m != nil {
		return m.MarginRatio
	}
	return ""
}

func (m *PositionHealth) GetMaintenanceMargin() string {
	if m != nil {
		return m.MaintenanceMargin
	}
	return ""
}

func (m *PositionHealth) GetAccountEquity() string {
	if m != nil {
		return m.AccountEquity
	}
	return ""
}

func (m *PositionHealth) GetIsHealthy() bool {
	if m != nil {
		return m.IsHealthy
	}
	return false
}

func (m *PositionHealth) GetAtRisk() bool {
	if m != nil {
		return m.AtRisk
	}
	return false
}

// GenesisState defines the clearinghouse module's genesis state
type GenesisState struct {
	Liquidations         []*Liquidation `protobuf:"bytes,1,rep,name=liquidations,proto3" json:"liquidations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fc35641f20b2178, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetLiquidations() []*Liquidation {
	if m != nil {
		return m.Liquidations
	}
	return nil
}

func init() {
	proto.RegisterEnum("perpdex.clearinghouse.v1.LiquidationStatus", LiquidationStatus_name, LiquidationStatus_value)
	proto.RegisterType((*Liquidation)(nil), "perpdex.clearinghouse.v1.Liquidation")
	proto.RegisterType((*PositionHealth)(nil), "perpdex.clearinghouse.v1.PositionHealth")
	proto.RegisterType((*GenesisState)(nil), "perpdex.clearinghouse.v1.GenesisState")
}

func init() {
	proto.RegisterFile("perpdex/clearinghouse/v1/types.proto", fileDescriptor_2fc35641f20b2178)
}

var fileDescriptor_2fc35641f20b2178 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x3c,
	0x18, 0x7d, 0xb3, 0xbe, 0x74, 0xed, 0xd3, 0x0f, 0xb5, 0xbe, 0x00, 0xc3, 0xd8, 0x56, 0x0a, 0x95,
	0x2a, 0xa6, 0xa5, 0xda, 0x26, 0x7e, 0x40, 0x69, 0xb2, 0x11, 0xa9, 0x94, 0x92, 0xb6, 0x12, 0x70,
	0x13, 0x79, 0x89, 0x69, 0xad, 0x36, 0x1f, 0xb3, 0x9d, 0x89, 0xec, 0x8f, 0x70, 0xc9, 0xbf, 0xe4,
	0x1a, 0xc5, 0xc9, 0xb4, 0x6c, 0x74, 0x12, 0x97, 0x3e, 0xe7, 0x3c, 0x8e, 0xcf, 0x39, 0x79, 0xe0,
	0x4d, 0x44, 0x79, 0xe4, 0xd1, 0x1f, 0x03, 0x77, 0x43, 0x09, 0x67, 0xc1, 0x72, 0x15, 0xc6, 0x82,
	0x0e, 0xae, 0x4f, 0x06, 0x32, 0x89, 0xa8, 0xd0, 0x23, 0x1e, 0xca, 0x10, 0xe1, 0x5c, 0xa5, 0xdf,
	0x53, 0xe9, 0xd7, 0x27, 0xdd, 0x5f, 0x25, 0xa8, 0x8d, 0xd9, 0x55, 0xcc, 0x3c, 0x22, 0x59, 0x18,
	0xa0, 0x1e, 0x34, 0x37, 0x77, 0x47, 0x87, 0x79, 0x58, 0xeb, 0x68, 0xfd, 0xaa, 0xdd, 0x28, 0xa0,
	0x96, 0x87, 0x9e, 0x42, 0x59, 0x72, 0xe2, 0x51, 0x8e, 0x77, 0x14, 0x9d, 0x9f, 0xd0, 0x1e, 0x54,
	0x7d, 0xc2, 0xd7, 0x54, 0xa6, 0x93, 0x25, 0x45, 0x55, 0x32, 0xc0, 0xf2, 0xd0, 0x6b, 0x68, 0x44,
	0xa1, 0x60, 0xea, 0x62, 0xc1, 0x6e, 0x28, 0xfe, 0x5f, 0x09, 0xea, 0xb7, 0xe0, 0x8c, 0xdd, 0x50,
	0x74, 0x08, 0x35, 0x1a, 0x48, 0x9e, 0x38, 0x11, 0x67, 0x2e, 0xc5, 0x4f, 0x94, 0x04, 0x14, 0x34,
	0x4d, 0x11, 0xb4, 0x0f, 0x90, 0xde, 0x98, 0xf3, 0x65, 0xc5, 0xab, 0x8f, 0x66, 0xf4, 0x11, 0xb4,
	0x8b, 0x06, 0x32, 0xd5, 0xae, 0x52, 0xb5, 0x0a, 0x44, 0x26, 0xee, 0x41, 0xd3, 0x27, 0x7c, 0xc9,
	0x02, 0xc7, 0xa3, 0xdf, 0x99, 0xcb, 0x24, 0xae, 0x64, 0x6e, 0x33, 0xd4, 0xc8, 0x40, 0x84, 0x61,
	0x37, 0xa2, 0x01, 0xd9, 0xc8, 0x04, 0x57, 0x15, 0x7f, 0x7b, 0x44, 0x23, 0x28, 0x0b, 0x49, 0x64,
	0x2c, 0x30, 0x74, 0xb4, 0x7e, 0xf3, 0xf4, 0x48, 0x7f, 0x2c, 0x69, 0xbd, 0x90, 0xf2, 0x4c, 0x8d,
	0xd8, 0xf9, 0x28, 0x7a, 0x09, 0x55, 0xc9, 0x7c, 0x2a, 0x24, 0xf1, 0x23, 0x5c, 0xeb, 0x68, 0xfd,
	0x92, 0x7d, 0x07, 0x74, 0x7f, 0x6b, 0xd0, 0x9c, 0xe6, 0x09, 0x7d, 0xa0, 0x64, 0x23, 0x57, 0x85,
	0xf4, 0xb5, 0xc7, 0xd3, 0xdf, 0x79, 0x90, 0xfe, 0x2b, 0xa8, 0xe7, 0x5e, 0x79, 0xfa, 0x88, 0xbc,
	0x9d, 0x5a, 0x86, 0xd9, 0x29, 0x84, 0x8e, 0x01, 0xf9, 0x84, 0x05, 0x92, 0x06, 0x24, 0x70, 0xa9,
	0x93, 0x51, 0x79, 0x4b, 0xed, 0x02, 0xf3, 0x51, 0x11, 0x69, 0x7a, 0xc4, 0x75, 0xc3, 0x38, 0x90,
	0x0e, 0xbd, 0x8a, 0x99, 0x4c, 0xf2, 0xb6, 0x1a, 0x39, 0x6a, 0x2a, 0x30, 0x2d, 0x8c, 0x09, 0x67,
	0xa5, 0x9e, 0x9e, 0xa8, 0xc2, 0x2a, 0x76, 0x95, 0x89, 0xcc, 0x4b, 0x82, 0x9e, 0xc1, 0x2e, 0x91,
	0x0e, 0x67, 0x62, 0xad, 0x6a, 0xaa, 0xd8, 0x65, 0x22, 0x6d, 0x26, 0xd6, 0xdd, 0xaf, 0x50, 0xbf,
	0xa0, 0x01, 0x15, 0x4c, 0xa4, 0x79, 0x51, 0x64, 0x41, 0xbd, 0x50, 0xa0, 0xc0, 0x5a, 0xa7, 0xd4,
	0xaf, 0x9d, 0xf6, 0xfe, 0x29, 0x71, 0xfb, 0xde, 0xe8, 0xdb, 0x9f, 0x1a, 0xb4, 0xff, 0xea, 0x03,
	0x75, 0xe1, 0x60, 0x6c, 0x7d, 0x5e, 0x58, 0xc6, 0x70, 0x6e, 0x7d, 0x9a, 0x38, 0xb3, 0xf9, 0x70,
	0xbe, 0x98, 0x39, 0x8b, 0xc9, 0x6c, 0x6a, 0x8e, 0xac, 0x73, 0xcb, 0x34, 0x5a, 0xff, 0xa1, 0x03,
	0x78, 0xb1, 0x45, 0x33, 0x35, 0x27, 0x86, 0x35, 0xb9, 0x68, 0x69, 0xe8, 0x10, 0xf6, 0xb6, 0xf0,
	0xe6, 0x17, 0x73, 0xb4, 0x98, 0x9b, 0x46, 0x6b, 0x07, 0xed, 0xc3, 0xf3, 0x2d, 0x82, 0xf3, 0xa1,
	0x35, 0x36, 0x8d, 0x56, 0xe9, 0xfd, 0xbb, 0x6f, 0x67, 0x4b, 0x26, 0x57, 0xf1, 0xa5, 0xee, 0x86,
	0xfe, 0x20, 0x54, 0xff, 0x59, 0xb4, 0x22, 0x83, 0xd4, 0xe4, 0x71, 0xba, 0xe7, 0x0f, 0x37, 0x5d,
	0xad, 0xf9, 0x65, 0x59, 0xed, 0xf9, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x52, 0x0c,
	0x08, 0x0f, 0x04, 0x00, 0x00,
}
