// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/perpetual/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryAccountRequest is the request for Account query
type QueryAccountRequest struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAccountRequest) Reset()         { *m = QueryAccountRequest{} }
func (m *QueryAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAccountRequest) ProtoMessage()    {}
func (*QueryAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{0}
}
func (m *QueryAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAccountRequest.Unmarshal(m, b)
}
func (m *QueryAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAccountRequest.Marshal(b, m, deterministic)
}
func (m *QueryAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountRequest.Merge(m, src)
}
func (m *QueryAccountRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAccountRequest.Size(m)
}
func (m *QueryAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountRequest proto.InternalMessageInfo

func (m *QueryAccountRequest) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

// QueryAccountResponse is the response for Account query
type QueryAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAccountResponse) Reset()         { *m = QueryAccountResponse{} }
func (m *QueryAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAccountResponse) ProtoMessage()    {}
func (*QueryAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{1}
}
func (m *QueryAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAccountResponse.Unmarshal(m, b)
}
func (m *QueryAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAccountResponse.Marshal(b, m, deterministic)
}
func (m *QueryAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountResponse.Merge(m, src)
}
func (m *QueryAccountResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAccountResponse.Size(m)
}
func (m *QueryAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountResponse proto.InternalMessageInfo

func (m *QueryAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// QueryPositionRequest is the request for Position query
type QueryPositionRequest struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPositionRequest) Reset()         { *m = QueryPositionRequest{} }
func (m *QueryPositionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPositionRequest) ProtoMessage()    {}
func (*QueryPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{2}
}
func (m *QueryPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPositionRequest.Unmarshal(m, b)
}
func (m *QueryPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPositionRequest.Marshal(b, m, deterministic)
}
func (m *QueryPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPositionRequest.Merge(m, src)
}
func (m *QueryPositionRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPositionRequest.Size(m)
}
func (m *QueryPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPositionRequest proto.InternalMessageInfo

func (m *QueryPositionRequest) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *QueryPositionRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// QueryPositionResponse is the response for Position query
type QueryPositionResponse struct {
	Position             *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryPositionResponse) Reset()         { *m = QueryPositionResponse{} }
func (m *QueryPositionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPositionResponse) ProtoMessage()    {}
func (*QueryPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{3}
}
func (m *QueryPositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPositionResponse.Unmarshal(m, b)
}
func (m *QueryPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPositionResponse.Marshal(b, m, deterministic)
}
func (m *QueryPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPositionResponse.Merge(m, src)
}
func (m *QueryPositionResponse) XXX_Size() int {
	return xxx_messageInfo_QueryPositionResponse.Size(m)
}
func (m *QueryPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPositionResponse proto.InternalMessageInfo

func (m *QueryPositionResponse) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

// QueryPositionsRequest is the request for Positions query
type QueryPositionsRequest struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPositionsRequest) Reset()         { *m = QueryPositionsRequest{} }
func (m *QueryPositionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPositionsRequest) ProtoMessage()    {}
func (*QueryPositionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{4}
}
func (m *QueryPositionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPositionsRequest.Unmarshal(m, b)
}
func (m *QueryPositionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPositionsRequest.Marshal(b, m, deterministic)
}
func (m *QueryPositionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPositionsRequest.Merge(m, src)
}
func (m *QueryPositionsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPositionsRequest.Size(m)
}
func (m *QueryPositionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPositionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPositionsRequest proto.InternalMessageInfo

func (m *QueryPositionsRequest) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

// QueryPositionsResponse is the response for Positions query
type QueryPositionsResponse struct {
	Positions            []*Position `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryPositionsResponse) Reset()         { *m = QueryPositionsResponse{} }
func (m *QueryPositionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPositionsResponse) ProtoMessage()    {}
func (*QueryPositionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{5}
}
func (m *QueryPositionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPositionsResponse.Unmarshal(m, b)
}
func (m *QueryPositionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPositionsResponse.Marshal(b, m, deterministic)
}
func (m *QueryPositionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPositionsResponse.Merge(m, src)
}
func (m *QueryPositionsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryPositionsResponse.Size(m)
}
func (m *QueryPositionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPositionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPositionsResponse proto.InternalMessageInfo

func (m *QueryPositionsResponse) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

// QueryMarketRequest is the request for Market query
type QueryMarketRequest struct {
	MarketId             string   `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMarketRequest) Reset()         { *m = QueryMarketRequest{} }
func (m *QueryMarketRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMarketRequest) ProtoMessage()    {}
func (*QueryMarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{6}
}
func (m *QueryMarketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMarketRequest.Unmarshal(m, b)
}
func (m *QueryMarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMarketRequest.Marshal(b, m, deterministic)
}
func (m *QueryMarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketRequest.Merge(m, src)
}
func (m *QueryMarketRequest) XXX_Size() int {
	return xxx_messageInfo_QueryMarketRequest.Size(m)
}
func (m *QueryMarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketRequest proto.InternalMessageInfo

func (m *QueryMarketRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// QueryMarketResponse is the response for Market query
type QueryMarketResponse struct {
	Market               *Market  `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMarketResponse) Reset()         { *m = QueryMarketResponse{} }
func (m *QueryMarketResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMarketResponse) ProtoMessage()    {}
func (*QueryMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{7}
}
func (m *QueryMarketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMarketResponse.Unmarshal(m, b)
}
func (m *QueryMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMarketResponse.Marshal(b, m, deterministic)
}
func (m *QueryMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketResponse.Merge(m, src)
}
func (m *QueryMarketResponse) XXX_Size() int {
	return xxx_messageInfo_QueryMarketResponse.Size(m)
}
func (m *QueryMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketResponse proto.InternalMessageInfo

func (m *QueryMarketResponse) GetMarket() *Market {
	if m != nil {
		return m.Market
	}
	return nil
}

// QueryMarketsRequest is the request for Markets query
type QueryMarketsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMarketsRequest) Reset()         { *m = QueryMarketsRequest{} }
func (m *QueryMarketsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMarketsRequest) ProtoMessage()    {}
func (*QueryMarketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{8}
}
func (m *QueryMarketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMarketsRequest.Unmarshal(m, b)
}
func (m *QueryMarketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMarketsRequest.Marshal(b, m, deterministic)
}
func (m *QueryMarketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketsRequest.Merge(m, src)
}
func (m *QueryMarketsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryMarketsRequest.Size(m)
}
func (m *QueryMarketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketsRequest proto.InternalMessageInfo

// QueryMarketsResponse is the response for Markets query
type QueryMarketsResponse struct {
	Markets              []*Market `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryMarketsResponse) Reset()         { *m = QueryMarketsResponse{} }
func (m *QueryMarketsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMarketsResponse) ProtoMessage()    {}
func (*QueryMarketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{9}
}
func (m *QueryMarketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMarketsResponse.Unmarshal(m, b)
}
func (m *QueryMarketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMarketsResponse.Marshal(b, m, deterministic)
}
func (m *QueryMarketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketsResponse.Merge(m, src)
}
func (m *QueryMarketsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryMarketsResponse.Size(m)
}
func (m *QueryMarketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketsResponse proto.InternalMessageInfo

func (m *QueryMarketsResponse) GetMarkets() []*Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

// QueryPriceRequest is the request for Price query
type QueryPriceRequest struct {
	MarketId             string   `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPriceRequest) Reset()         { *m = QueryPriceRequest{} }
func (m *QueryPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPriceRequest) ProtoMessage()    {}
func (*QueryPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{10}
}
func (m *QueryPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPriceRequest.Unmarshal(m, b)
}
func (m *QueryPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPriceRequest.Marshal(b, m, deterministic)
}
func (m *QueryPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPriceRequest.Merge(m, src)
}
func (m *QueryPriceRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPriceRequest.Size(m)
}
func (m *QueryPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPriceRequest proto.InternalMessageInfo

func (m *QueryPriceRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// QueryPriceResponse is the response for Price query
type QueryPriceResponse struct {
	Price                *PriceInfo `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryPriceResponse) Reset()         { *m = QueryPriceResponse{} }
func (m *QueryPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPriceResponse) ProtoMessage()    {}
func (*QueryPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_761172367806c578, []int{11}
}
func (m *QueryPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPriceResponse.Unmarshal(m, b)
}
func (m *QueryPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPriceResponse.Marshal(b, m, deterministic)
}
func (m *QueryPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPriceResponse.Merge(m, src)
}
func (m *QueryPriceResponse) XXX_Size() int {
	return xxx_messageInfo_QueryPriceResponse.Size(m)
}
func (m *QueryPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPriceResponse proto.InternalMessageInfo

func (m *QueryPriceResponse) GetPrice() *PriceInfo {
	if m != nil {
		return m.Price
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryAccountRequest)(nil), "perpdex.perpetual.v1.QueryAccountRequest")
	proto.RegisterType((*QueryAccountResponse)(nil), "perpdex.perpetual.v1.QueryAccountResponse")
	proto.RegisterType((*QueryPositionRequest)(nil), "perpdex.perpetual.v1.QueryPositionRequest")
	proto.RegisterType((*QueryPositionResponse)(nil), "perpdex.perpetual.v1.QueryPositionResponse")
	proto.RegisterType((*QueryPositionsRequest)(nil), "perpdex.perpetual.v1.QueryPositionsRequest")
	proto.RegisterType((*QueryPositionsResponse)(nil), "perpdex.perpetual.v1.QueryPositionsResponse")
	proto.RegisterType((*QueryMarketRequest)(nil), "perpdex.perpetual.v1.QueryMarketRequest")
	proto.RegisterType((*QueryMarketResponse)(nil), "perpdex.perpetual.v1.QueryMarketResponse")
	proto.RegisterType((*QueryMarketsRequest)(nil), "perpdex.perpetual.v1.QueryMarketsRequest")
	proto.RegisterType((*QueryMarketsResponse)(nil), "perpdex.perpetual.v1.QueryMarketsResponse")
	proto.RegisterType((*QueryPriceRequest)(nil), "perpdex.perpetual.v1.QueryPriceRequest")
	proto.RegisterType((*QueryPriceResponse)(nil), "perpdex.perpetual.v1.QueryPriceResponse")
}

func init() { proto.RegisterFile("perpdex/perpetual/v1/query.proto", fileDescriptor_761172367806c578) }

var fileDescriptor_761172367806c578 = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xa2, 0xe6, 0xcf, 0x70, 0x62, 0x68, 0xab, 0xc8, 0xb4, 0x34, 0x5a, 0x09, 0x9a,
	0x14, 0xea, 0x6d, 0x5a, 0x0a, 0x12, 0x70, 0x81, 0x5b, 0x55, 0xf1, 0x2f, 0x48, 0x1c, 0xb8, 0x20,
	0x37, 0x59, 0x52, 0x8b, 0xd4, 0xeb, 0xda, 0x9b, 0x8a, 0xaa, 0xea, 0xa5, 0x17, 0x0e, 0x1c, 0x40,
	0xe2, 0xc2, 0x91, 0x77, 0xe2, 0x15, 0x78, 0x10, 0xe4, 0xdd, 0x59, 0x37, 0xb1, 0x5c, 0xc7, 0xa7,
	0xaa, 0x9b, 0xef, 0x9b, 0xf9, 0xed, 0xb7, 0x33, 0x32, 0xb4, 0x23, 0x11, 0x47, 0x43, 0xf1, 0x95,
	0xa7, 0x7f, 0x85, 0x9a, 0xf8, 0x63, 0x7e, 0xda, 0xe3, 0x27, 0x13, 0x11, 0x9f, 0x79, 0x51, 0x2c,
	0x95, 0xc4, 0x25, 0x52, 0x78, 0x99, 0xc2, 0x3b, 0xed, 0xb9, 0xab, 0x23, 0x29, 0x47, 0x63, 0xc1,
	0xfd, 0x28, 0xe0, 0x7e, 0x18, 0x4a, 0xe5, 0xab, 0x40, 0x86, 0x89, 0xf1, 0xb8, 0xc5, 0x55, 0xd5,
	0x59, 0x24, 0x48, 0xc1, 0xb6, 0xe0, 0xf6, 0xbb, 0xb4, 0xc9, 0x8b, 0xc1, 0x40, 0x4e, 0x42, 0xd5,
	0x17, 0x27, 0x13, 0x91, 0x28, 0x5c, 0x81, 0x9a, 0x8a, 0xfd, 0xa1, 0x88, 0x5b, 0x4e, 0xdb, 0xe9,
	0x34, 0xfb, 0xf4, 0x1f, 0x7b, 0x03, 0x4b, 0xb3, 0xf2, 0x24, 0x92, 0x61, 0x22, 0xf0, 0x09, 0xd4,
	0x7d, 0x73, 0xa4, 0x0d, 0x37, 0x77, 0xd6, 0xbc, 0x22, 0x5c, 0xcf, 0xfa, 0xac, 0x9a, 0x1d, 0x50,
	0xc1, 0xb7, 0x32, 0x09, 0x52, 0xf2, 0x39, 0x00, 0x78, 0x07, 0x9a, 0xc7, 0x7e, 0xfc, 0x45, 0xa8,
	0x4f, 0xc1, 0xb0, 0xb5, 0xa0, 0x7f, 0x6a, 0x98, 0x83, 0xfd, 0x21, 0x7b, 0x0f, 0xcb, 0xb9, 0x62,
	0x84, 0xf7, 0x14, 0x1a, 0x11, 0x9d, 0x11, 0xdf, 0xdd, 0x62, 0xbe, 0xcc, 0x99, 0xe9, 0x19, 0xcf,
	0x15, 0x4d, 0xe6, 0x65, 0xf4, 0x01, 0x56, 0xf2, 0x06, 0xc2, 0x78, 0x0e, 0x4d, 0x5b, 0x36, 0x69,
	0x39, 0xed, 0x1b, 0x15, 0x38, 0xae, 0x0c, 0xac, 0x07, 0xa8, 0xeb, 0xbe, 0xd2, 0xd7, 0xb5, 0x14,
	0x33, 0x81, 0x38, 0xb9, 0x40, 0x0e, 0xe8, 0x75, 0xad, 0x85, 0x38, 0x1e, 0x41, 0xcd, 0x48, 0x28,
	0x8c, 0xd5, 0x62, 0x08, 0x72, 0x91, 0x96, 0x2d, 0xcf, 0x14, 0xb3, 0x31, 0xb0, 0xd7, 0xf4, 0x82,
	0xd9, 0x31, 0x35, 0x79, 0x0c, 0x75, 0x63, 0xb4, 0x57, 0x2d, 0xef, 0x62, 0xc5, 0x6c, 0x1b, 0x6e,
	0x99, 0xf8, 0xe2, 0x60, 0x20, 0x2a, 0xde, 0x12, 0xa7, 0x1d, 0xd4, 0x7f, 0x0f, 0x16, 0xa3, 0xf4,
	0x80, 0xee, 0xb8, 0x7e, 0x4d, 0xd0, 0xa9, 0x64, 0x3f, 0xfc, 0x2c, 0xfb, 0x46, 0xbd, 0x73, 0x59,
	0x87, 0x45, 0x5d, 0x0d, 0x7f, 0x3a, 0x50, 0xa7, 0x79, 0xc5, 0x6e, 0xb1, 0xbb, 0x60, 0x75, 0xdc,
	0xcd, 0x2a, 0x52, 0xc3, 0xc8, 0xbc, 0xcb, 0xbf, 0xff, 0x7e, 0x2d, 0x74, 0xf0, 0x3e, 0x2f, 0x5c,
	0x54, 0x5a, 0x12, 0x7e, 0x6e, 0x26, 0xeb, 0x02, 0xff, 0x38, 0xd0, 0xb0, 0xa3, 0x81, 0x65, 0x8d,
	0x72, 0xeb, 0xe4, 0x3e, 0xa8, 0xa4, 0x25, 0xaa, 0x67, 0x9a, 0x6a, 0x0f, 0x77, 0x8b, 0xa9, 0xec,
	0x44, 0x66, 0x58, 0xfc, 0x3c, 0x7b, 0x9b, 0x0b, 0xfc, 0xed, 0x40, 0x33, 0x9b, 0x7c, 0xac, 0xd2,
	0xd7, 0x4e, 0x92, 0xfb, 0xb0, 0x9a, 0x98, 0x28, 0xb7, 0x35, 0xe5, 0x26, 0x76, 0xca, 0x29, 0x93,
	0xab, 0xf4, 0x7e, 0x38, 0x50, 0x33, 0xd3, 0x86, 0x9d, 0x92, 0x56, 0x33, 0xfb, 0xe5, 0x76, 0x2b,
	0x28, 0xab, 0x11, 0x99, 0x90, 0x66, 0xc2, 0xfa, 0xe6, 0x40, 0x9d, 0xf6, 0x06, 0xe7, 0x37, 0x4a,
	0xaa, 0x8c, 0x58, 0x6e, 0x0d, 0xd9, 0x3d, 0x0d, 0xb5, 0x8e, 0x6b, 0x65, 0x50, 0x09, 0x7e, 0x77,
	0x60, 0x51, 0xef, 0x02, 0x6e, 0x94, 0xbd, 0xc2, 0xd4, 0x4e, 0xba, 0x9d, 0xf9, 0x42, 0x62, 0xe0,
	0x9a, 0xa1, 0x8b, 0x1b, 0xd7, 0x3c, 0x55, 0x2a, 0x9e, 0xce, 0xe5, 0x65, 0xef, 0x23, 0x1f, 0x05,
	0xea, 0x68, 0x72, 0xe8, 0x0d, 0xe4, 0x31, 0x97, 0x91, 0x08, 0xfd, 0x71, 0x74, 0xe4, 0x6b, 0xdb,
	0x56, 0xea, 0x9f, 0xae, 0xa0, 0x3f, 0x67, 0x87, 0x35, 0xfd, 0x3d, 0xdb, 0xfd, 0x1f, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0xac, 0x8c, 0xae, 0x49, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Account returns a trader's account information
	Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error)
	// Position returns a trader's position in a market
	Position(ctx context.Context, in *QueryPositionRequest, opts ...grpc.CallOption) (*QueryPositionResponse, error)
	// Positions returns all positions for a trader
	Positions(ctx context.Context, in *QueryPositionsRequest, opts ...grpc.CallOption) (*QueryPositionsResponse, error)
	// Market returns market configuration
	Market(ctx context.Context, in *QueryMarketRequest, opts ...grpc.CallOption) (*QueryMarketResponse, error)
	// Markets returns all markets
	Markets(ctx context.Context, in *QueryMarketsRequest, opts ...grpc.CallOption) (*QueryMarketsResponse, error)
	// Price returns current price information
	Price(ctx context.Context, in *QueryPriceRequest, opts ...grpc.CallOption) (*QueryPriceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error) {
	out := new(QueryAccountResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Query/Account", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Position(ctx context.Context, in *QueryPositionRequest, opts ...grpc.CallOption) (*QueryPositionResponse, error) {
	out := new(QueryPositionResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Query/Position", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Positions(ctx context.Context, in *QueryPositionsRequest, opts ...grpc.CallOption) (*QueryPositionsResponse, error) {
	out := new(QueryPositionsResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Query/Positions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Market(ctx context.Context, in *QueryMarketRequest, opts ...grpc.CallOption) (*QueryMarketResponse, error) {
	out := new(QueryMarketResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Query/Market", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Markets(ctx context.Context, in *QueryMarketsRequest, opts ...grpc.CallOption) (*QueryMarketsResponse, error) {
	out := new(QueryMarketsResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Query/Markets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Price(ctx context.Context, in *QueryPriceRequest, opts ...grpc.CallOption) (*QueryPriceResponse, error) {
	out := new(QueryPriceResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Query/Price", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Account returns a trader's account information
	Account(context.Context, *QueryAccountRequest) (*QueryAccountResponse, error)
	// Position returns a trader's position in a market
	Position(context.Context, *QueryPositionRequest) (*QueryPositionResponse, error)
	// Positions returns all positions for a trader
	Positions(context.Context, *QueryPositionsRequest) (*QueryPositionsResponse, error)
	// Market returns market configuration
	Market(context.Context, *QueryMarketRequest) (*QueryMarketResponse, error)
	// Markets returns all markets
	Markets(context.Context, *QueryMarketsRequest) (*QueryMarketsResponse, error)
	// Price returns current price information
	Price(context.Context, *QueryPriceRequest) (*QueryPriceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Account(ctx context.Context, req *QueryAccountRequest) (*QueryAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Account not implemented")
}
func (*UnimplementedQueryServer) Position(ctx context.Context, req *QueryPositionRequest) (*QueryPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Position not implemented")
}
func (*UnimplementedQueryServer) Positions(ctx context.Context, req *QueryPositionsRequest) (*QueryPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Positions not implemented")
}
func (*UnimplementedQueryServer) Market(ctx context.Context, req *QueryMarketRequest) (*QueryMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Market not implemented")
}
func (*UnimplementedQueryServer) Markets(ctx context.Context, req *QueryMarketsRequest) (*QueryMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Markets not implemented")
}
func (*UnimplementedQueryServer) Price(ctx context.Context, req *QueryPriceRequest) (*QueryPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Price not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Query/Account",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Account(ctx, req.(*QueryAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Position_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Position(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Query/Position",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Position(ctx, req.(*QueryPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Positions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Positions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Query/Positions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Positions(ctx, req.(*QueryPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Market_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Market(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Query/Market",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Market(ctx, req.(*QueryMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Markets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Markets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Query/Markets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Markets(ctx, req.(*QueryMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Price_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Price(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Query/Price",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Price(ctx, req.(*QueryPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.perpetual.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Account",
			Handler:    _Query_Account_Handler,
		},
		{
			MethodName: "Position",
			Handler:    _Query_Position_Handler,
		},
		{
			MethodName: "Positions",
			Handler:    _Query_Positions_Handler,
		},
		{
			MethodName: "Market",
			Handler:    _Query_Market_Handler,
		},
		{
			MethodName: "Markets",
			Handler:    _Query_Markets_Handler,
		},
		{
			MethodName: "Price",
			Handler:    _Query_Price_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/perpetual/v1/query.proto",
}
