// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/perpetual/v1/tx.proto

package types

import (
	context "context"
	_ "cosmossdk.io/api/cosmos/msg/v1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgDeposit defines the Deposit request
type MsgDeposit struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDeposit) Reset()         { *m = MsgDeposit{} }
func (m *MsgDeposit) String() string { return proto.CompactTextString(m) }
func (*MsgDeposit) ProtoMessage()    {}
func (*MsgDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_f997cdf2ff9d399d, []int{0}
}
func (m *MsgDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeposit.Unmarshal(m, b)
}
func (m *MsgDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeposit.Marshal(b, m, deterministic)
}
func (m *MsgDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeposit.Merge(m, src)
}
func (m *MsgDeposit) XXX_Size() int {
	return xxx_messageInfo_MsgDeposit.Size(m)
}
func (m *MsgDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeposit proto.InternalMessageInfo

func (m *MsgDeposit) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *MsgDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// MsgDepositResponse defines the Deposit response
type MsgDepositResponse struct {
	NewBalance           string   `protobuf:"bytes,1,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDepositResponse) Reset()         { *m = MsgDepositResponse{} }
func (m *MsgDepositResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDepositResponse) ProtoMessage()    {}
func (*MsgDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f997cdf2ff9d399d, []int{1}
}
func (m *MsgDepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDepositResponse.Unmarshal(m, b)
}
func (m *MsgDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDepositResponse.Marshal(b, m, deterministic)
}
func (m *MsgDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDepositResponse.Merge(m, src)
}
func (m *MsgDepositResponse) XXX_Size() int {
	return xxx_messageInfo_MsgDepositResponse.Size(m)
}
func (m *MsgDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDepositResponse proto.InternalMessageInfo

func (m *MsgDepositResponse) GetNewBalance() string {
	if m != nil {
		return m.NewBalance
	}
	return ""
}

// MsgWithdraw defines the Withdraw request
type MsgWithdraw struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgWithdraw) Reset()         { *m = MsgWithdraw{} }
func (m *MsgWithdraw) String() string { return proto.CompactTextString(m) }
func (*MsgWithdraw) ProtoMessage()    {}
func (*MsgWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_f997cdf2ff9d399d, []int{2}
}
func (m *MsgWithdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWithdraw.Unmarshal(m, b)
}
func (m *MsgWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWithdraw.Marshal(b, m, deterministic)
}
func (m *MsgWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdraw.Merge(m, src)
}
func (m *MsgWithdraw) XXX_Size() int {
	return xxx_messageInfo_MsgWithdraw.Size(m)
}
func (m *MsgWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdraw proto.InternalMessageInfo

func (m *MsgWithdraw) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *MsgWithdraw) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// MsgWithdrawResponse defines the Withdraw response
type MsgWithdrawResponse struct {
	NewBalance           string   `protobuf:"bytes,1,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgWithdrawResponse) Reset()         { *m = MsgWithdrawResponse{} }
func (m *MsgWithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawResponse) ProtoMessage()    {}
func (*MsgWithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f997cdf2ff9d399d, []int{3}
}
func (m *MsgWithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgWithdrawResponse.Unmarshal(m, b)
}
func (m *MsgWithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgWithdrawResponse.Marshal(b, m, deterministic)
}
func (m *MsgWithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawResponse.Merge(m, src)
}
func (m *MsgWithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_MsgWithdrawResponse.Size(m)
}
func (m *MsgWithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawResponse proto.InternalMessageInfo

func (m *MsgWithdrawResponse) GetNewBalance() string {
	if m != nil {
		return m.NewBalance
	}
	return ""
}

// MsgUpdatePrice defines the UpdatePrice request (for oracle simulation)
type MsgUpdatePrice struct {
	Authority            string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	MarkPrice            string   `protobuf:"bytes,3,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	IndexPrice           string   `protobuf:"bytes,4,opt,name=index_price,json=indexPrice,proto3" json:"index_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUpdatePrice) Reset()         { *m = MsgUpdatePrice{} }
func (m *MsgUpdatePrice) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePrice) ProtoMessage()    {}
func (*MsgUpdatePrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_f997cdf2ff9d399d, []int{4}
}
func (m *MsgUpdatePrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUpdatePrice.Unmarshal(m, b)
}
func (m *MsgUpdatePrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUpdatePrice.Marshal(b, m, deterministic)
}
func (m *MsgUpdatePrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePrice.Merge(m, src)
}
func (m *MsgUpdatePrice) XXX_Size() int {
	return xxx_messageInfo_MsgUpdatePrice.Size(m)
}
func (m *MsgUpdatePrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePrice proto.InternalMessageInfo

func (m *MsgUpdatePrice) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdatePrice) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *MsgUpdatePrice) GetMarkPrice() string {
	if m != nil {
		return m.MarkPrice
	}
	return ""
}

func (m *MsgUpdatePrice) GetIndexPrice() string {
	if m != nil {
		return m.IndexPrice
	}
	return ""
}

// MsgUpdatePriceResponse defines the UpdatePrice response
type MsgUpdatePriceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUpdatePriceResponse) Reset()         { *m = MsgUpdatePriceResponse{} }
func (m *MsgUpdatePriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePriceResponse) ProtoMessage()    {}
func (*MsgUpdatePriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f997cdf2ff9d399d, []int{5}
}
func (m *MsgUpdatePriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUpdatePriceResponse.Unmarshal(m, b)
}
func (m *MsgUpdatePriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUpdatePriceResponse.Marshal(b, m, deterministic)
}
func (m *MsgUpdatePriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePriceResponse.Merge(m, src)
}
func (m *MsgUpdatePriceResponse) XXX_Size() int {
	return xxx_messageInfo_MsgUpdatePriceResponse.Size(m)
}
func (m *MsgUpdatePriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePriceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgDeposit)(nil), "perpdex.perpetual.v1.MsgDeposit")
	proto.RegisterType((*MsgDepositResponse)(nil), "perpdex.perpetual.v1.MsgDepositResponse")
	proto.RegisterType((*MsgWithdraw)(nil), "perpdex.perpetual.v1.MsgWithdraw")
	proto.RegisterType((*MsgWithdrawResponse)(nil), "perpdex.perpetual.v1.MsgWithdrawResponse")
	proto.RegisterType((*MsgUpdatePrice)(nil), "perpdex.perpetual.v1.MsgUpdatePrice")
	proto.RegisterType((*MsgUpdatePriceResponse)(nil), "perpdex.perpetual.v1.MsgUpdatePriceResponse")
}

func init() { proto.RegisterFile("perpdex/perpetual/v1/tx.proto", fileDescriptor_f997cdf2ff9d399d) }

var fileDescriptor_f997cdf2ff9d399d = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0x16, 0x42, 0x33, 0x91, 0x90, 0x30, 0x55, 0x31, 0x86, 0xa8, 0xc1, 0xe2, 0x50,
	0xa2, 0xc6, 0x26, 0x54, 0xf4, 0xd0, 0x1b, 0x11, 0x17, 0x0e, 0x91, 0x50, 0x50, 0x05, 0xe2, 0x12,
	0x6d, 0xb2, 0x23, 0x67, 0x45, 0xbc, 0xbb, 0xda, 0xdd, 0x34, 0xe9, 0x0d, 0x21, 0xc4, 0x81, 0xa7,
	0xe0, 0x11, 0x72, 0xe0, 0x49, 0x38, 0xf2, 0x02, 0x79, 0x0d, 0x64, 0xaf, 0x1d, 0x1b, 0x48, 0x95,
	0x1e, 0x7a, 0x49, 0x3c, 0x33, 0xdf, 0xee, 0x3f, 0xf3, 0x7b, 0x0c, 0x4d, 0x89, 0x4a, 0x52, 0x5c,
	0x44, 0xe9, 0x3f, 0x9a, 0x19, 0x99, 0x46, 0x17, 0xdd, 0xc8, 0x2c, 0x42, 0xa9, 0x84, 0x11, 0xee,
	0x7e, 0x5e, 0x0e, 0xd7, 0xe5, 0xf0, 0xa2, 0xeb, 0x3f, 0x18, 0x0b, 0x9d, 0x08, 0x1d, 0x25, 0x3a,
	0x4e, 0xe9, 0x44, 0xc7, 0x16, 0xf7, 0x1f, 0xda, 0xc2, 0x30, 0x8b, 0x22, 0x1b, 0xe4, 0xa5, 0x7b,
	0x24, 0x61, 0x5c, 0x44, 0xd9, 0xaf, 0x4d, 0x05, 0x5f, 0x1d, 0x80, 0xbe, 0x8e, 0x5f, 0xa3, 0x14,
	0x9a, 0x19, 0xf7, 0x39, 0xd4, 0x8c, 0x22, 0x14, 0x95, 0xe7, 0xb4, 0x9c, 0xa3, 0x7a, 0xcf, 0xfb,
	0xf5, 0xb3, 0xb3, 0x9f, 0xdf, 0xf1, 0x8a, 0x52, 0x85, 0x5a, 0xbf, 0x33, 0x8a, 0xf1, 0x78, 0x90,
	0x73, 0xee, 0x01, 0xd4, 0x48, 0x22, 0x66, 0xdc, 0x78, 0x3b, 0xe9, 0x89, 0x41, 0x1e, 0x9d, 0x1d,
	0x7f, 0x59, 0x2d, 0xdb, 0x39, 0xf4, 0x7d, 0xb5, 0x6c, 0x3f, 0xfe, 0x7f, 0xc8, 0x52, 0x37, 0x78,
	0x09, 0x6e, 0x19, 0x0d, 0x50, 0x4b, 0xc1, 0x35, 0xba, 0x87, 0xd0, 0xe0, 0x38, 0x1f, 0x8e, 0xc8,
	0x94, 0xf0, 0x31, 0xda, 0x96, 0x06, 0xc0, 0x71, 0xde, 0xb3, 0x99, 0xe0, 0x9b, 0x03, 0x8d, 0xbe,
	0x8e, 0xdf, 0x33, 0x33, 0xa1, 0x8a, 0xcc, 0x6f, 0xb0, 0xfd, 0xce, 0x3f, 0xed, 0x37, 0x37, 0xb6,
	0x5f, 0x08, 0x07, 0xa7, 0x70, 0xbf, 0x12, 0x5e, 0x7f, 0x80, 0xdf, 0x0e, 0xdc, 0xed, 0xeb, 0xf8,
	0x5c, 0x52, 0x62, 0xf0, 0xad, 0x62, 0x63, 0x74, 0x4f, 0xa1, 0x4e, 0x66, 0x66, 0x22, 0x14, 0x33,
	0x97, 0x5b, 0xc7, 0x28, 0x51, 0xf7, 0x11, 0xd4, 0x13, 0xa2, 0x3e, 0xa1, 0x19, 0x32, 0x9a, 0x0f,
	0xb3, 0x67, 0x13, 0x6f, 0xa8, 0xdb, 0x04, 0x48, 0x9f, 0x87, 0x32, 0x95, 0xf0, 0x76, 0xb3, 0x6a,
	0x86, 0x5b, 0xcd, 0x43, 0x68, 0x30, 0x4e, 0x71, 0x91, 0xd7, 0x6f, 0xd9, 0x3e, 0xb3, 0x54, 0x06,
	0x9c, 0x9d, 0xa4, 0x76, 0x94, 0x62, 0xa9, 0x23, 0xad, 0x8d, 0x8e, 0x54, 0x26, 0x09, 0x3c, 0x38,
	0xf8, 0x3b, 0x53, 0xf8, 0xf2, 0xe2, 0xc7, 0x0e, 0xec, 0xf6, 0x75, 0xec, 0x9e, 0xc3, 0x9d, 0x62,
	0xf3, 0x5a, 0xe1, 0xa6, 0x35, 0x0f, 0xcb, 0xad, 0xf0, 0x8f, 0xb6, 0x11, 0x6b, 0xdb, 0x3f, 0xc0,
	0xde, 0x7a, 0x25, 0x9e, 0x5c, 0x79, 0xaa, 0x40, 0xfc, 0x67, 0x5b, 0x91, 0xf5, 0xcd, 0x04, 0x1a,
	0xd5, 0x77, 0xf5, 0xf4, 0xca, 0x93, 0x15, 0xca, 0x3f, 0xbe, 0x0e, 0x55, 0x48, 0xf8, 0xb7, 0x3f,
	0xaf, 0x96, 0x6d, 0xa7, 0xd7, 0xfd, 0x18, 0xc5, 0xcc, 0x4c, 0x66, 0xa3, 0x70, 0x2c, 0x92, 0x48,
	0x48, 0xe4, 0x64, 0x2a, 0x27, 0x24, 0x73, 0xbb, 0x93, 0xda, 0x5e, 0x35, 0xde, 0x5c, 0x4a, 0xd4,
	0xa3, 0x5a, 0xf6, 0x49, 0x9f, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x96, 0x65, 0x71, 0x50,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Deposit deposits margin into the account
	Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgDepositResponse, error)
	// Withdraw withdraws margin from the account
	Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error)
	// UpdatePrice updates the mark price (oracle simulation)
	UpdatePrice(ctx context.Context, in *MsgUpdatePrice, opts ...grpc.CallOption) (*MsgUpdatePriceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Deposit(ctx context.Context, in *MsgDeposit, opts ...grpc.CallOption) (*MsgDepositResponse, error) {
	out := new(MsgDepositResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Msg/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Withdraw(ctx context.Context, in *MsgWithdraw, opts ...grpc.CallOption) (*MsgWithdrawResponse, error) {
	out := new(MsgWithdrawResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Msg/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePrice(ctx context.Context, in *MsgUpdatePrice, opts ...grpc.CallOption) (*MsgUpdatePriceResponse, error) {
	out := new(MsgUpdatePriceResponse)
	err := c.cc.Invoke(ctx, "/perpdex.perpetual.v1.Msg/UpdatePrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Deposit deposits margin into the account
	Deposit(context.Context, *MsgDeposit) (*MsgDepositResponse, error)
	// Withdraw withdraws margin from the account
	Withdraw(context.Context, *MsgWithdraw) (*MsgWithdrawResponse, error)
	// UpdatePrice updates the mark price (oracle simulation)
	UpdatePrice(context.Context, *MsgUpdatePrice) (*MsgUpdatePriceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Deposit(ctx context.Context, req *MsgDeposit) (*MsgDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (*UnimplementedMsgServer) Withdraw(ctx context.Context, req *MsgWithdraw) (*MsgWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedMsgServer) UpdatePrice(ctx context.Context, req *MsgUpdatePrice) (*MsgUpdatePriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePrice not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Msg/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Deposit(ctx, req.(*MsgDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdraw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Msg/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Withdraw(ctx, req.(*MsgWithdraw))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.perpetual.v1.Msg/UpdatePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePrice(ctx, req.(*MsgUpdatePrice))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.perpetual.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deposit",
			Handler:    _Msg_Deposit_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _Msg_Withdraw_Handler,
		},
		{
			MethodName: "UpdatePrice",
			Handler:    _Msg_UpdatePrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/perpetual/v1/tx.proto",
}
