// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/perpetual/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PositionSide represents the position direction
type PositionSide int32

const (
	PositionSide_POSITION_SIDE_UNSPECIFIED PositionSide = 0
	PositionSide_POSITION_SIDE_LONG        PositionSide = 1
	PositionSide_POSITION_SIDE_SHORT       PositionSide = 2
)

var PositionSide_name = map[int32]string{
	0: "POSITION_SIDE_UNSPECIFIED",
	1: "POSITION_SIDE_LONG",
	2: "POSITION_SIDE_SHORT",
}

var PositionSide_value = map[string]int32{
	"POSITION_SIDE_UNSPECIFIED": 0,
	"POSITION_SIDE_LONG":        1,
	"POSITION_SIDE_SHORT":       2,
}

func (x PositionSide) String() string {
	return proto.EnumName(PositionSide_name, int32(x))
}

func (PositionSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56db9efc6a5a109f, []int{0}
}

// Market defines a perpetual trading market
type Market struct {
	MarketId              string   `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BaseAsset             string   `protobuf:"bytes,2,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset            string   `protobuf:"bytes,3,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	MaxLeverage           string   `protobuf:"bytes,4,opt,name=max_leverage,json=maxLeverage,proto3" json:"max_leverage,omitempty"`
	InitialMarginRate     string   `protobuf:"bytes,5,opt,name=initial_margin_rate,json=initialMarginRate,proto3" json:"initial_margin_rate,omitempty"`
	MaintenanceMarginRate string   `protobuf:"bytes,6,opt,name=maintenance_margin_rate,json=maintenanceMarginRate,proto3" json:"maintenance_margin_rate,omitempty"`
	TakerFeeRate          string   `protobuf:"bytes,7,opt,name=taker_fee_rate,json=takerFeeRate,proto3" json:"taker_fee_rate,omitempty"`
	MakerFeeRate          string   `protobuf:"bytes,8,opt,name=maker_fee_rate,json=makerFeeRate,proto3" json:"maker_fee_rate,omitempty"`
	TickSize              string   `protobuf:"bytes,9,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
	LotSize               string   `protobuf:"bytes,10,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	IsActive              bool     `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_56db9efc6a5a109f, []int{0}
}
func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *Market) GetBaseAsset() string {
	if m != nil {
		return m.BaseAsset
	}
	return ""
}

func (m *Market) GetQuoteAsset() string {
	if m != nil {
		return m.QuoteAsset
	}
	return ""
}

func (m *Market) GetMaxLeverage() string {
	if m != nil {
		return m.MaxLeverage
	}
	return ""
}

func (m *Market) GetInitialMarginRate() string {
	if m != nil {
		return m.InitialMarginRate
	}
	return ""
}

func (m *Market) GetMaintenanceMarginRate() string {
	if m != nil {
		return m.MaintenanceMarginRate
	}
	return ""
}

func (m *Market) GetTakerFeeRate() string {
	if m != nil {
		return m.TakerFeeRate
	}
	return ""
}

func (m *Market) GetMakerFeeRate() string {
	if m != nil {
		return m.MakerFeeRate
	}
	return ""
}

func (m *Market) GetTickSize() string {
	if m != nil {
		return m.TickSize
	}
	return ""
}

func (m *Market) GetLotSize() string {
	if m != nil {
		return m.LotSize
	}
	return ""
}

func (m *Market) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

// Position represents a trader's position in a market
type Position struct {
	Trader               string       `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string       `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side                 PositionSide `protobuf:"varint,3,opt,name=side,proto3,enum=perpdex.perpetual.v1.PositionSide" json:"side,omitempty"`
	Size_                string       `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	EntryPrice           string       `protobuf:"bytes,5,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	Margin               string       `protobuf:"bytes,6,opt,name=margin,proto3" json:"margin,omitempty"`
	Leverage             string       `protobuf:"bytes,7,opt,name=leverage,proto3" json:"leverage,omitempty"`
	UnrealizedPnl        string       `protobuf:"bytes,8,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	LiquidationPrice     string       `protobuf:"bytes,9,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	OpenedAt             int64        `protobuf:"varint,10,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_56db9efc6a5a109f, []int{1}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Position) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *Position) GetSide() PositionSide {
	if m != nil {
		return m.Side
	}
	return PositionSide_POSITION_SIDE_UNSPECIFIED
}

func (m *Position) GetSize_() string {
	if m != nil {
		return m.Size_
	}
	return ""
}

func (m *Position) GetEntryPrice() string {
	if m != nil {
		return m.EntryPrice
	}
	return ""
}

func (m *Position) GetMargin() string {
	if m != nil {
		return m.Margin
	}
	return ""
}

func (m *Position) GetLeverage() string {
	if m != nil {
		return m.Leverage
	}
	return ""
}

func (m *Position) GetUnrealizedPnl() string {
	if m != nil {
		return m.UnrealizedPnl
	}
	return ""
}

func (m *Position) GetLiquidationPrice() string {
	if m != nil {
		return m.LiquidationPrice
	}
	return ""
}

func (m *Position) GetOpenedAt() int64 {
	if m != nil {
		return m.OpenedAt
	}
	return 0
}

func (m *Position) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// Account represents a trader's margin account
type Account struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	Balance              string   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	LockedMargin         string   `protobuf:"bytes,3,opt,name=locked_margin,json=lockedMargin,proto3" json:"locked_margin,omitempty"`
	UnrealizedPnl        string   `protobuf:"bytes,4,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	TotalEquity          string   `protobuf:"bytes,5,opt,name=total_equity,json=totalEquity,proto3" json:"total_equity,omitempty"`
	MarginRatio          string   `protobuf:"bytes,6,opt,name=margin_ratio,json=marginRatio,proto3" json:"margin_ratio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_56db9efc6a5a109f, []int{2}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Account) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Account) GetLockedMargin() string {
	if m != nil {
		return m.LockedMargin
	}
	return ""
}

func (m *Account) GetUnrealizedPnl() string {
	if m != nil {
		return m.UnrealizedPnl
	}
	return ""
}

func (m *Account) GetTotalEquity() string {
	if m != nil {
		return m.TotalEquity
	}
	return ""
}

func (m *Account) GetMarginRatio() string {
	if m != nil {
		return m.MarginRatio
	}
	return ""
}

// PriceInfo represents the current price information
type PriceInfo struct {
	MarketId             string   `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	MarkPrice            string   `protobuf:"bytes,2,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	IndexPrice           string   `protobuf:"bytes,3,opt,name=index_price,json=indexPrice,proto3" json:"index_price,omitempty"`
	LastPrice            string   `protobuf:"bytes,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceInfo) Reset()         { *m = PriceInfo{} }
func (m *PriceInfo) String() string { return proto.CompactTextString(m) }
func (*PriceInfo) ProtoMessage()    {}
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56db9efc6a5a109f, []int{3}
}
func (m *PriceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceInfo.Unmarshal(m, b)
}
func (m *PriceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceInfo.Marshal(b, m, deterministic)
}
func (m *PriceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceInfo.Merge(m, src)
}
func (m *PriceInfo) XXX_Size() int {
	return xxx_messageInfo_PriceInfo.Size(m)
}
func (m *PriceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PriceInfo proto.InternalMessageInfo

func (m *PriceInfo) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *PriceInfo) GetMarkPrice() string {
	if m != nil {
		return m.MarkPrice
	}
	return ""
}

func (m *PriceInfo) GetIndexPrice() string {
	if m != nil {
		return m.IndexPrice
	}
	return ""
}

func (m *PriceInfo) GetLastPrice() string {
	if m != nil {
		return m.LastPrice
	}
	return ""
}

func (m *PriceInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// GenesisState defines the perpetual module's genesis state
type GenesisState struct {
	Markets              []*Market    `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	Positions            []*Position  `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	Accounts             []*Account   `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Prices               []*PriceInfo `protobuf:"bytes,4,rep,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_56db9efc6a5a109f, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetMarkets() []*Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

func (m *GenesisState) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *GenesisState) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *GenesisState) GetPrices() []*PriceInfo {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto.RegisterEnum("perpdex.perpetual.v1.PositionSide", PositionSide_name, PositionSide_value)
	proto.RegisterType((*Market)(nil), "perpdex.perpetual.v1.Market")
	proto.RegisterType((*Position)(nil), "perpdex.perpetual.v1.Position")
	proto.RegisterType((*Account)(nil), "perpdex.perpetual.v1.Account")
	proto.RegisterType((*PriceInfo)(nil), "perpdex.perpetual.v1.PriceInfo")
	proto.RegisterType((*GenesisState)(nil), "perpdex.perpetual.v1.GenesisState")
}

func init() { proto.RegisterFile("perpdex/perpetual/v1/types.proto", fileDescriptor_56db9efc6a5a109f) }

var fileDescriptor_56db9efc6a5a109f = []byte{
	// 789 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x5d, 0x8f, 0xdb, 0x44,
	0x14, 0xc5, 0x49, 0x48, 0xec, 0xeb, 0x74, 0x95, 0x4e, 0xa1, 0x75, 0x49, 0xc3, 0xa6, 0x01, 0xa4,
	0x15, 0x88, 0x44, 0x5b, 0xa4, 0x22, 0x24, 0x5e, 0x02, 0x4d, 0x4b, 0xa4, 0x76, 0x13, 0x39, 0xe5,
	0x85, 0x07, 0xac, 0x89, 0x7d, 0x77, 0x77, 0x14, 0x7f, 0xad, 0x67, 0x1c, 0x65, 0xf3, 0x2f, 0xf8,
	0x11, 0xfc, 0x1c, 0xfe, 0x0b, 0x8f, 0x3c, 0xa2, 0xf9, 0x70, 0x36, 0x41, 0x59, 0xfa, 0x94, 0x99,
	0x73, 0xce, 0x95, 0x67, 0xce, 0x3d, 0x37, 0x03, 0xfd, 0x1c, 0x8b, 0x3c, 0xc2, 0xcd, 0x48, 0xfe,
	0xa2, 0x28, 0x69, 0x3c, 0x5a, 0x9f, 0x8f, 0xc4, 0x6d, 0x8e, 0x7c, 0x98, 0x17, 0x99, 0xc8, 0xc8,
	0x27, 0x46, 0x31, 0xdc, 0x29, 0x86, 0xeb, 0xf3, 0xc1, 0x1f, 0x75, 0x68, 0xbe, 0xa3, 0xc5, 0x0a,
	0x05, 0xe9, 0x82, 0x93, 0xa8, 0x55, 0xc0, 0x22, 0xcf, 0xea, 0x5b, 0x67, 0x8e, 0x6f, 0x6b, 0x60,
	0x1a, 0x91, 0x1e, 0xc0, 0x92, 0x72, 0x0c, 0x28, 0xe7, 0x28, 0xbc, 0x9a, 0x62, 0x1d, 0x89, 0x8c,
	0x25, 0x40, 0x4e, 0xc1, 0xbd, 0x29, 0x33, 0x51, 0xf1, 0x75, 0xc5, 0x83, 0x82, 0xb4, 0xe0, 0x39,
	0xb4, 0x13, 0xba, 0x09, 0x62, 0x5c, 0x63, 0x41, 0xaf, 0xd0, 0x6b, 0x28, 0x85, 0x9b, 0xd0, 0xcd,
	0x5b, 0x03, 0x91, 0x21, 0x3c, 0x62, 0x29, 0x13, 0x8c, 0xc6, 0x41, 0x42, 0x8b, 0x2b, 0x96, 0x06,
	0x05, 0x15, 0xe8, 0x7d, 0xac, 0x94, 0x0f, 0x0d, 0xf5, 0x4e, 0x31, 0x3e, 0x15, 0x48, 0x5e, 0xc2,
	0x93, 0x84, 0xb2, 0x54, 0x60, 0x4a, 0xd3, 0x10, 0x0f, 0x6a, 0x9a, 0xaa, 0xe6, 0xd3, 0x3d, 0x7a,
	0xaf, 0xee, 0x4b, 0x38, 0x11, 0x74, 0x85, 0x45, 0x70, 0x89, 0xa8, 0xe5, 0x2d, 0x25, 0x6f, 0x2b,
	0xf4, 0x35, 0x62, 0xa5, 0x4a, 0x0e, 0x55, 0xb6, 0x56, 0x25, 0xfb, 0xaa, 0x2e, 0x38, 0x82, 0x85,
	0xab, 0x80, 0xb3, 0x2d, 0x7a, 0x8e, 0xf6, 0x4c, 0x02, 0x0b, 0xb6, 0x45, 0xf2, 0x14, 0xec, 0x38,
	0x13, 0x9a, 0x03, 0xc5, 0xb5, 0xe2, 0x4c, 0x28, 0xaa, 0x0b, 0x0e, 0xe3, 0x01, 0x0d, 0x05, 0x5b,
	0xa3, 0xe7, 0xf6, 0xad, 0x33, 0xdb, 0xb7, 0x19, 0x1f, 0xab, 0xfd, 0xe0, 0xef, 0x1a, 0xd8, 0xf3,
	0x8c, 0x33, 0xc1, 0xb2, 0x94, 0x3c, 0x86, 0xa6, 0x28, 0x68, 0x84, 0x85, 0x69, 0x89, 0xd9, 0x1d,
	0x76, 0xab, 0xf6, 0x9f, 0x6e, 0xbd, 0x84, 0x06, 0x67, 0x11, 0xaa, 0x3e, 0x9c, 0xbc, 0x18, 0x0c,
	0x8f, 0xb5, 0x7e, 0x58, 0x7d, 0x62, 0xc1, 0x22, 0xf4, 0x95, 0x9e, 0x10, 0x59, 0xb7, 0xad, 0xba,
	0xa3, 0xd6, 0xb2, 0xb5, 0x98, 0x8a, 0xe2, 0x36, 0xc8, 0x0b, 0x16, 0x56, 0xed, 0x00, 0x05, 0xcd,
	0x25, 0x22, 0x4f, 0xa8, 0xbd, 0x37, 0xb6, 0x9b, 0x1d, 0xf9, 0x0c, 0xec, 0x5d, 0xbb, 0xb5, 0xc3,
	0xbb, 0x3d, 0xf9, 0x0a, 0x4e, 0xca, 0xb4, 0x40, 0x1a, 0xb3, 0x2d, 0x46, 0x41, 0x9e, 0xc6, 0xc6,
	0xdd, 0x07, 0x77, 0xe8, 0x3c, 0x8d, 0xc9, 0x37, 0xf0, 0x30, 0x66, 0x37, 0x25, 0x8b, 0xa8, 0x3c,
	0xa8, 0x39, 0x81, 0xb6, 0xb9, 0xb3, 0x47, 0xe8, 0x73, 0x74, 0xc1, 0xc9, 0x72, 0x4c, 0x31, 0x0a,
	0xa8, 0x50, 0x7e, 0xd7, 0x7d, 0x5b, 0x03, 0x63, 0x21, 0xf3, 0x5b, 0xe6, 0x11, 0x15, 0x9a, 0x75,
	0x15, 0xeb, 0x18, 0x64, 0x2c, 0x06, 0x7f, 0x59, 0xd0, 0x1a, 0x87, 0x61, 0x56, 0xa6, 0xe2, 0x5e,
	0xc7, 0x3d, 0x68, 0x2d, 0x69, 0x2c, 0xc3, 0x64, 0xfc, 0xae, 0xb6, 0xe4, 0x0b, 0x78, 0x10, 0x67,
	0xe1, 0x0a, 0x23, 0x13, 0x42, 0x93, 0xff, 0xb6, 0x06, 0x75, 0xf4, 0x8e, 0x5c, 0xb9, 0x71, 0xec,
	0xca, 0xcf, 0xa1, 0x2d, 0x32, 0x41, 0xe3, 0x00, 0x6f, 0x4a, 0x26, 0x6e, 0x8d, 0xdf, 0xae, 0xc2,
	0x26, 0x0a, 0xd2, 0xb3, 0x54, 0x85, 0x9d, 0x65, 0xc6, 0x76, 0x37, 0xa9, 0x22, 0xce, 0xb2, 0xc1,
	0x9f, 0x16, 0x38, 0xca, 0x95, 0x69, 0x7a, 0x99, 0x7d, 0x70, 0xb2, 0xe5, 0xda, 0x98, 0x6b, 0x26,
	0x5b, 0x22, 0xda, 0xd5, 0x53, 0x70, 0x59, 0x1a, 0xe1, 0xc6, 0xf0, 0x66, 0xb2, 0x15, 0xa4, 0x05,
	0x3d, 0x80, 0x98, 0x72, 0x61, 0x78, 0x7d, 0x27, 0x47, 0x22, 0x9a, 0x7e, 0x26, 0x27, 0x24, 0x41,
	0x2e, 0x68, 0x92, 0xab, 0xcb, 0xd4, 0xfd, 0x3b, 0x60, 0xf0, 0x8f, 0x05, 0xed, 0x37, 0x98, 0x22,
	0x67, 0x7c, 0x21, 0xf4, 0x50, 0xb7, 0xf4, 0xc9, 0xb8, 0x67, 0xf5, 0xeb, 0x67, 0xee, 0x8b, 0x67,
	0xc7, 0xc3, 0xab, 0xff, 0xb3, 0xfc, 0x4a, 0x4c, 0x7e, 0x04, 0x27, 0x37, 0x79, 0xe6, 0x5e, 0x4d,
	0x55, 0x7e, 0xfe, 0xff, 0xb1, 0xf7, 0xef, 0x0a, 0xc8, 0x0f, 0x60, 0x53, 0xdd, 0x7d, 0xee, 0xd5,
	0x55, 0x71, 0xef, 0x78, 0xb1, 0xc9, 0x88, 0xbf, 0x93, 0x93, 0xef, 0xa1, 0xa9, 0x6e, 0xce, 0xbd,
	0x86, 0x2a, 0x3c, 0xbd, 0xe7, 0xab, 0x55, 0x33, 0x7c, 0x23, 0xff, 0xfa, 0x77, 0x68, 0xef, 0x4f,
	0x20, 0xe9, 0xc1, 0xd3, 0xf9, 0x6c, 0x31, 0x7d, 0x3f, 0x9d, 0x5d, 0x04, 0x8b, 0xe9, 0xab, 0x49,
	0xf0, 0xeb, 0xc5, 0x62, 0x3e, 0xf9, 0x79, 0xfa, 0x7a, 0x3a, 0x79, 0xd5, 0xf9, 0x88, 0x3c, 0x06,
	0x72, 0x48, 0xbf, 0x9d, 0x5d, 0xbc, 0xe9, 0x58, 0xe4, 0x09, 0x3c, 0x3a, 0xc4, 0x17, 0xbf, 0xcc,
	0xfc, 0xf7, 0x9d, 0xda, 0x4f, 0xe7, 0xbf, 0x8d, 0xae, 0x98, 0xb8, 0x2e, 0x97, 0xc3, 0x30, 0x4b,
	0x46, 0x72, 0x10, 0x68, 0x9c, 0x5f, 0x53, 0xf5, 0x40, 0x7c, 0x2b, 0x5f, 0x8a, 0xfd, 0xb7, 0x42,
	0x3d, 0x14, 0xcb, 0xa6, 0x7a, 0x29, 0xbe, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xd8, 0xb0,
	0x71, 0x4d, 0x06, 0x00, 0x00,
}
