// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/orderbook/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryOrderBookRequest is the request for the OrderBook query
type QueryOrderBookRequest struct {
	MarketId             string   `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Depth                uint32   `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderBookRequest) Reset()         { *m = QueryOrderBookRequest{} }
func (m *QueryOrderBookRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOrderBookRequest) ProtoMessage()    {}
func (*QueryOrderBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{0}
}
func (m *QueryOrderBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderBookRequest.Unmarshal(m, b)
}
func (m *QueryOrderBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderBookRequest.Marshal(b, m, deterministic)
}
func (m *QueryOrderBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderBookRequest.Merge(m, src)
}
func (m *QueryOrderBookRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOrderBookRequest.Size(m)
}
func (m *QueryOrderBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderBookRequest proto.InternalMessageInfo

func (m *QueryOrderBookRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *QueryOrderBookRequest) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

// QueryOrderBookResponse is the response for the OrderBook query
type QueryOrderBookResponse struct {
	OrderBook            *OrderBook `protobuf:"bytes,1,opt,name=order_book,json=orderBook,proto3" json:"order_book,omitempty"`
	BestBid              string     `protobuf:"bytes,2,opt,name=best_bid,json=bestBid,proto3" json:"best_bid,omitempty"`
	BestAsk              string     `protobuf:"bytes,3,opt,name=best_ask,json=bestAsk,proto3" json:"best_ask,omitempty"`
	Spread               string     `protobuf:"bytes,4,opt,name=spread,proto3" json:"spread,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryOrderBookResponse) Reset()         { *m = QueryOrderBookResponse{} }
func (m *QueryOrderBookResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOrderBookResponse) ProtoMessage()    {}
func (*QueryOrderBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{1}
}
func (m *QueryOrderBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderBookResponse.Unmarshal(m, b)
}
func (m *QueryOrderBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderBookResponse.Marshal(b, m, deterministic)
}
func (m *QueryOrderBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderBookResponse.Merge(m, src)
}
func (m *QueryOrderBookResponse) XXX_Size() int {
	return xxx_messageInfo_QueryOrderBookResponse.Size(m)
}
func (m *QueryOrderBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderBookResponse proto.InternalMessageInfo

func (m *QueryOrderBookResponse) GetOrderBook() *OrderBook {
	if m != nil {
		return m.OrderBook
	}
	return nil
}

func (m *QueryOrderBookResponse) GetBestBid() string {
	if m != nil {
		return m.BestBid
	}
	return ""
}

func (m *QueryOrderBookResponse) GetBestAsk() string {
	if m != nil {
		return m.BestAsk
	}
	return ""
}

func (m *QueryOrderBookResponse) GetSpread() string {
	if m != nil {
		return m.Spread
	}
	return ""
}

// QueryOrderRequest is the request for the Order query
type QueryOrderRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderRequest) Reset()         { *m = QueryOrderRequest{} }
func (m *QueryOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOrderRequest) ProtoMessage()    {}
func (*QueryOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{2}
}
func (m *QueryOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderRequest.Unmarshal(m, b)
}
func (m *QueryOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderRequest.Marshal(b, m, deterministic)
}
func (m *QueryOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderRequest.Merge(m, src)
}
func (m *QueryOrderRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOrderRequest.Size(m)
}
func (m *QueryOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderRequest proto.InternalMessageInfo

func (m *QueryOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

// QueryOrderResponse is the response for the Order query
type QueryOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderResponse) Reset()         { *m = QueryOrderResponse{} }
func (m *QueryOrderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOrderResponse) ProtoMessage()    {}
func (*QueryOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{3}
}
func (m *QueryOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderResponse.Unmarshal(m, b)
}
func (m *QueryOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderResponse.Marshal(b, m, deterministic)
}
func (m *QueryOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderResponse.Merge(m, src)
}
func (m *QueryOrderResponse) XXX_Size() int {
	return xxx_messageInfo_QueryOrderResponse.Size(m)
}
func (m *QueryOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderResponse proto.InternalMessageInfo

func (m *QueryOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

// QueryOrdersRequest is the request for the Orders query
type QueryOrdersRequest struct {
	Trader               string      `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string      `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Status               OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=perpdex.orderbook.v1.OrderStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryOrdersRequest) Reset()         { *m = QueryOrdersRequest{} }
func (m *QueryOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOrdersRequest) ProtoMessage()    {}
func (*QueryOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{4}
}
func (m *QueryOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrdersRequest.Unmarshal(m, b)
}
func (m *QueryOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrdersRequest.Marshal(b, m, deterministic)
}
func (m *QueryOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrdersRequest.Merge(m, src)
}
func (m *QueryOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_QueryOrdersRequest.Size(m)
}
func (m *QueryOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrdersRequest proto.InternalMessageInfo

func (m *QueryOrdersRequest) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *QueryOrdersRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *QueryOrdersRequest) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

// QueryOrdersResponse is the response for the Orders query
type QueryOrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrdersResponse) Reset()         { *m = QueryOrdersResponse{} }
func (m *QueryOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOrdersResponse) ProtoMessage()    {}
func (*QueryOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{5}
}
func (m *QueryOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrdersResponse.Unmarshal(m, b)
}
func (m *QueryOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrdersResponse.Marshal(b, m, deterministic)
}
func (m *QueryOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrdersResponse.Merge(m, src)
}
func (m *QueryOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_QueryOrdersResponse.Size(m)
}
func (m *QueryOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrdersResponse proto.InternalMessageInfo

func (m *QueryOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

// QueryTradesRequest is the request for the Trades query
type QueryTradesRequest struct {
	MarketId             string   `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTradesRequest) Reset()         { *m = QueryTradesRequest{} }
func (m *QueryTradesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTradesRequest) ProtoMessage()    {}
func (*QueryTradesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{6}
}
func (m *QueryTradesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTradesRequest.Unmarshal(m, b)
}
func (m *QueryTradesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTradesRequest.Marshal(b, m, deterministic)
}
func (m *QueryTradesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTradesRequest.Merge(m, src)
}
func (m *QueryTradesRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTradesRequest.Size(m)
}
func (m *QueryTradesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTradesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTradesRequest proto.InternalMessageInfo

func (m *QueryTradesRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *QueryTradesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// QueryTradesResponse is the response for the Trades query
type QueryTradesResponse struct {
	Trades               []*Trade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTradesResponse) Reset()         { *m = QueryTradesResponse{} }
func (m *QueryTradesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTradesResponse) ProtoMessage()    {}
func (*QueryTradesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7e80bed1291996c, []int{7}
}
func (m *QueryTradesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTradesResponse.Unmarshal(m, b)
}
func (m *QueryTradesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTradesResponse.Marshal(b, m, deterministic)
}
func (m *QueryTradesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTradesResponse.Merge(m, src)
}
func (m *QueryTradesResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTradesResponse.Size(m)
}
func (m *QueryTradesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTradesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTradesResponse proto.InternalMessageInfo

func (m *QueryTradesResponse) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryOrderBookRequest)(nil), "perpdex.orderbook.v1.QueryOrderBookRequest")
	proto.RegisterType((*QueryOrderBookResponse)(nil), "perpdex.orderbook.v1.QueryOrderBookResponse")
	proto.RegisterType((*QueryOrderRequest)(nil), "perpdex.orderbook.v1.QueryOrderRequest")
	proto.RegisterType((*QueryOrderResponse)(nil), "perpdex.orderbook.v1.QueryOrderResponse")
	proto.RegisterType((*QueryOrdersRequest)(nil), "perpdex.orderbook.v1.QueryOrdersRequest")
	proto.RegisterType((*QueryOrdersResponse)(nil), "perpdex.orderbook.v1.QueryOrdersResponse")
	proto.RegisterType((*QueryTradesRequest)(nil), "perpdex.orderbook.v1.QueryTradesRequest")
	proto.RegisterType((*QueryTradesResponse)(nil), "perpdex.orderbook.v1.QueryTradesResponse")
}

func init() { proto.RegisterFile("perpdex/orderbook/v1/query.proto", fileDescriptor_c7e80bed1291996c) }

var fileDescriptor_c7e80bed1291996c = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xb6, 0x71, 0xe3, 0x41, 0x20, 0xb1, 0x94, 0x28, 0x4d, 0x91, 0x08, 0x96, 0xa0,
	0x81, 0x12, 0x9b, 0x24, 0x27, 0x2e, 0x48, 0xe4, 0x82, 0xda, 0x0b, 0xc2, 0x70, 0xe2, 0x12, 0x6d,
	0xf0, 0x2a, 0xb1, 0xf2, 0x67, 0xb7, 0xde, 0x4d, 0x45, 0x15, 0xe5, 0x82, 0x38, 0x21, 0x24, 0x0e,
	0x1c, 0xb9, 0xf3, 0x42, 0x7d, 0x05, 0x1e, 0x04, 0x79, 0x76, 0xed, 0x24, 0x95, 0x65, 0xe7, 0x96,
	0x89, 0xbf, 0xf9, 0xe6, 0x37, 0xbb, 0x9f, 0x0d, 0x4d, 0xc1, 0x62, 0x11, 0xb2, 0xaf, 0x3e, 0x8f,
	0x43, 0x16, 0x0f, 0x39, 0x9f, 0xf8, 0x57, 0x1d, 0xff, 0x72, 0xc1, 0xe2, 0x6b, 0x4f, 0xc4, 0x5c,
	0x71, 0x72, 0x64, 0x14, 0x5e, 0xa6, 0xf0, 0xae, 0x3a, 0x8d, 0x47, 0x23, 0xce, 0x47, 0x53, 0xe6,
	0x53, 0x11, 0xf9, 0x74, 0x3e, 0xe7, 0x8a, 0xaa, 0x88, 0xcf, 0xa5, 0xee, 0x69, 0xe4, 0xbb, 0xaa,
	0x6b, 0xc1, 0x8c, 0xc2, 0xbd, 0x80, 0x87, 0x1f, 0x92, 0x21, 0xef, 0x13, 0x41, 0x9f, 0xf3, 0x49,
	0xc0, 0x2e, 0x17, 0x4c, 0x2a, 0x72, 0x02, 0xce, 0x8c, 0xc6, 0x13, 0xa6, 0x06, 0x51, 0x58, 0xb7,
	0x9a, 0x56, 0xcb, 0x09, 0xaa, 0xfa, 0x8f, 0xf3, 0x90, 0x1c, 0x41, 0x25, 0x64, 0x42, 0x8d, 0xeb,
	0x7b, 0x4d, 0xab, 0x75, 0x37, 0xd0, 0x85, 0xfb, 0xd7, 0x82, 0xda, 0x6d, 0x33, 0x29, 0xf8, 0x5c,
	0x32, 0xf2, 0x06, 0x00, 0x11, 0x06, 0x09, 0x03, 0xda, 0xdd, 0xe9, 0x3e, 0xf6, 0xf2, 0x36, 0xf2,
	0xd6, 0xcd, 0x0e, 0x4f, 0x7f, 0x92, 0x63, 0xa8, 0x0e, 0x99, 0x54, 0x83, 0x61, 0x14, 0xe2, 0x4c,
	0x27, 0x38, 0x4c, 0xea, 0x7e, 0x14, 0x66, 0x8f, 0xa8, 0x9c, 0xd4, 0xf7, 0xd7, 0x8f, 0xde, 0xca,
	0x09, 0xa9, 0x81, 0x2d, 0x45, 0xcc, 0x68, 0x58, 0x3f, 0xc0, 0x07, 0xa6, 0x72, 0x3d, 0xb8, 0xbf,
	0xe6, 0x4c, 0x17, 0x3e, 0x86, 0xaa, 0x46, 0xcc, 0xf6, 0x3d, 0xc4, 0xfa, 0x3c, 0x74, 0xdf, 0x01,
	0xd9, 0xd4, 0x9b, 0x9d, 0x3a, 0x50, 0x41, 0x81, 0x59, 0xe7, 0xa4, 0x60, 0x9d, 0x40, 0x2b, 0xdd,
	0xef, 0xd6, 0xa6, 0x93, 0x4c, 0x47, 0xd7, 0xc0, 0x56, 0x31, 0x4d, 0xad, 0x9c, 0xc0, 0x54, 0xdb,
	0x77, 0xb0, 0x77, 0xeb, 0x0e, 0x5e, 0x83, 0x2d, 0x15, 0x55, 0x0b, 0x89, 0x5b, 0xdf, 0xeb, 0x3e,
	0x29, 0x98, 0xff, 0x11, 0x85, 0x81, 0x69, 0x70, 0x2f, 0xe0, 0xc1, 0x16, 0x85, 0x59, 0xa8, 0x07,
	0x36, 0xb6, 0xca, 0xba, 0xd5, 0xdc, 0x2f, 0xdb, 0xc8, 0x48, 0xb3, 0xb3, 0xf9, 0x94, 0x20, 0xcb,
	0x5d, 0xd3, 0x33, 0x8d, 0x66, 0x91, 0x4a, 0xd3, 0x83, 0x45, 0x06, 0x95, 0x1a, 0xad, 0xa1, 0xf0,
	0x34, 0x4a, 0xa0, 0xb0, 0xcb, 0x1c, 0x9c, 0xec, 0xde, 0x1c, 0x40, 0x05, 0xcd, 0xc8, 0x1f, 0x0b,
	0x9c, 0x2c, 0x51, 0xe4, 0x2c, 0xbf, 0x39, 0xf7, 0x0d, 0x68, 0xbc, 0xdc, 0x4d, 0xac, 0x39, 0xdd,
	0xde, 0xb7, 0x9b, 0x7f, 0xbf, 0xf7, 0xda, 0xe4, 0xcc, 0xcf, 0x7d, 0xe7, 0xd6, 0xc5, 0x32, 0x3b,
	0x98, 0x15, 0xf9, 0x61, 0x41, 0x05, 0xad, 0xc8, 0x69, 0xd9, 0xb0, 0x94, 0xaa, 0x55, 0x2e, 0x34,
	0x44, 0x1e, 0x12, 0xb5, 0xc8, 0xb3, 0x02, 0x22, 0x7f, 0x99, 0x66, 0x7e, 0x45, 0x7e, 0x5a, 0x60,
	0xeb, 0x44, 0x90, 0xd2, 0x21, 0xe9, 0x45, 0x37, 0x9e, 0xef, 0xa0, 0x34, 0x3c, 0x6d, 0xe4, 0x39,
	0x25, 0x4f, 0x0b, 0x78, 0xa4, 0xbf, 0xd4, 0xd9, 0x5f, 0x91, 0x5f, 0x16, 0xd8, 0x3a, 0x0b, 0x85,
	0x38, 0x5b, 0xb9, 0x2b, 0xc4, 0xd9, 0x0e, 0x96, 0xfb, 0x0a, 0x71, 0x5e, 0x90, 0x56, 0x3e, 0x8e,
	0x4e, 0xd2, 0xe6, 0x6d, 0xf5, 0x3b, 0x9f, 0xfd, 0x51, 0xa4, 0xc6, 0x8b, 0xa1, 0xf7, 0x85, 0xcf,
	0x7c, 0x2e, 0xd8, 0x9c, 0x4e, 0xc5, 0x98, 0x62, 0x7f, 0x3b, 0x31, 0xd8, 0xb4, 0xc0, 0x8f, 0xec,
	0xd0, 0xc6, 0xaf, 0x6c, 0xef, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xa0, 0x65, 0xe4, 0xdf,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// OrderBook returns the order book for a market
	OrderBook(ctx context.Context, in *QueryOrderBookRequest, opts ...grpc.CallOption) (*QueryOrderBookResponse, error)
	// Order returns a specific order by ID
	Order(ctx context.Context, in *QueryOrderRequest, opts ...grpc.CallOption) (*QueryOrderResponse, error)
	// Orders returns all orders for a trader
	Orders(ctx context.Context, in *QueryOrdersRequest, opts ...grpc.CallOption) (*QueryOrdersResponse, error)
	// Trades returns recent trades for a market
	Trades(ctx context.Context, in *QueryTradesRequest, opts ...grpc.CallOption) (*QueryTradesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) OrderBook(ctx context.Context, in *QueryOrderBookRequest, opts ...grpc.CallOption) (*QueryOrderBookResponse, error) {
	out := new(QueryOrderBookResponse)
	err := c.cc.Invoke(ctx, "/perpdex.orderbook.v1.Query/OrderBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Order(ctx context.Context, in *QueryOrderRequest, opts ...grpc.CallOption) (*QueryOrderResponse, error) {
	out := new(QueryOrderResponse)
	err := c.cc.Invoke(ctx, "/perpdex.orderbook.v1.Query/Order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Orders(ctx context.Context, in *QueryOrdersRequest, opts ...grpc.CallOption) (*QueryOrdersResponse, error) {
	out := new(QueryOrdersResponse)
	err := c.cc.Invoke(ctx, "/perpdex.orderbook.v1.Query/Orders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Trades(ctx context.Context, in *QueryTradesRequest, opts ...grpc.CallOption) (*QueryTradesResponse, error) {
	out := new(QueryTradesResponse)
	err := c.cc.Invoke(ctx, "/perpdex.orderbook.v1.Query/Trades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// OrderBook returns the order book for a market
	OrderBook(context.Context, *QueryOrderBookRequest) (*QueryOrderBookResponse, error)
	// Order returns a specific order by ID
	Order(context.Context, *QueryOrderRequest) (*QueryOrderResponse, error)
	// Orders returns all orders for a trader
	Orders(context.Context, *QueryOrdersRequest) (*QueryOrdersResponse, error)
	// Trades returns recent trades for a market
	Trades(context.Context, *QueryTradesRequest) (*QueryTradesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) OrderBook(ctx context.Context, req *QueryOrderBookRequest) (*QueryOrderBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderBook not implemented")
}
func (*UnimplementedQueryServer) Order(ctx context.Context, req *QueryOrderRequest) (*QueryOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Order not implemented")
}
func (*UnimplementedQueryServer) Orders(ctx context.Context, req *QueryOrdersRequest) (*QueryOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Orders not implemented")
}
func (*UnimplementedQueryServer) Trades(ctx context.Context, req *QueryTradesRequest) (*QueryTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trades not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_OrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.orderbook.v1.Query/OrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OrderBook(ctx, req.(*QueryOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.orderbook.v1.Query/Order",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Order(ctx, req.(*QueryOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Orders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Orders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.orderbook.v1.Query/Orders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Orders(ctx, req.(*QueryOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Trades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Trades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.orderbook.v1.Query/Trades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Trades(ctx, req.(*QueryTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.orderbook.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderBook",
			Handler:    _Query_OrderBook_Handler,
		},
		{
			MethodName: "Order",
			Handler:    _Query_Order_Handler,
		},
		{
			MethodName: "Orders",
			Handler:    _Query_Orders_Handler,
		},
		{
			MethodName: "Trades",
			Handler:    _Query_Trades_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/orderbook/v1/query.proto",
}
