// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/orderbook/v1/tx.proto

package types

import (
	context "context"
	_ "cosmossdk.io/api/cosmos/msg/v1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgPlaceOrder defines the PlaceOrder request
type MsgPlaceOrder struct {
	Trader               string    `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string    `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side                 Side      `protobuf:"varint,3,opt,name=side,proto3,enum=perpdex.orderbook.v1.Side" json:"side,omitempty"`
	OrderType            OrderType `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=perpdex.orderbook.v1.OrderType" json:"order_type,omitempty"`
	Price                string    `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string    `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MsgPlaceOrder) Reset()         { *m = MsgPlaceOrder{} }
func (m *MsgPlaceOrder) String() string { return proto.CompactTextString(m) }
func (*MsgPlaceOrder) ProtoMessage()    {}
func (*MsgPlaceOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_648f734bf0b553a4, []int{0}
}
func (m *MsgPlaceOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlaceOrder.Unmarshal(m, b)
}
func (m *MsgPlaceOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlaceOrder.Marshal(b, m, deterministic)
}
func (m *MsgPlaceOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlaceOrder.Merge(m, src)
}
func (m *MsgPlaceOrder) XXX_Size() int {
	return xxx_messageInfo_MsgPlaceOrder.Size(m)
}
func (m *MsgPlaceOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlaceOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlaceOrder proto.InternalMessageInfo

func (m *MsgPlaceOrder) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *MsgPlaceOrder) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *MsgPlaceOrder) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *MsgPlaceOrder) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *MsgPlaceOrder) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *MsgPlaceOrder) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

// MsgPlaceOrderResponse defines the PlaceOrder response
type MsgPlaceOrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FilledQty            string   `protobuf:"bytes,2,opt,name=filled_qty,json=filledQty,proto3" json:"filled_qty,omitempty"`
	AvgPrice             string   `protobuf:"bytes,3,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Trades               []*Trade `protobuf:"bytes,4,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPlaceOrderResponse) Reset()         { *m = MsgPlaceOrderResponse{} }
func (m *MsgPlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPlaceOrderResponse) ProtoMessage()    {}
func (*MsgPlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_648f734bf0b553a4, []int{1}
}
func (m *MsgPlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlaceOrderResponse.Unmarshal(m, b)
}
func (m *MsgPlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlaceOrderResponse.Marshal(b, m, deterministic)
}
func (m *MsgPlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlaceOrderResponse.Merge(m, src)
}
func (m *MsgPlaceOrderResponse) XXX_Size() int {
	return xxx_messageInfo_MsgPlaceOrderResponse.Size(m)
}
func (m *MsgPlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlaceOrderResponse proto.InternalMessageInfo

func (m *MsgPlaceOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *MsgPlaceOrderResponse) GetFilledQty() string {
	if m != nil {
		return m.FilledQty
	}
	return ""
}

func (m *MsgPlaceOrderResponse) GetAvgPrice() string {
	if m != nil {
		return m.AvgPrice
	}
	return ""
}

func (m *MsgPlaceOrderResponse) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

// MsgCancelOrder defines the CancelOrder request
type MsgCancelOrder struct {
	Trader               string   `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCancelOrder) Reset()         { *m = MsgCancelOrder{} }
func (m *MsgCancelOrder) String() string { return proto.CompactTextString(m) }
func (*MsgCancelOrder) ProtoMessage()    {}
func (*MsgCancelOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_648f734bf0b553a4, []int{2}
}
func (m *MsgCancelOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCancelOrder.Unmarshal(m, b)
}
func (m *MsgCancelOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCancelOrder.Marshal(b, m, deterministic)
}
func (m *MsgCancelOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelOrder.Merge(m, src)
}
func (m *MsgCancelOrder) XXX_Size() int {
	return xxx_messageInfo_MsgCancelOrder.Size(m)
}
func (m *MsgCancelOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelOrder proto.InternalMessageInfo

func (m *MsgCancelOrder) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *MsgCancelOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

// MsgCancelOrderResponse defines the CancelOrder response
type MsgCancelOrderResponse struct {
	CancelledQty         string   `protobuf:"bytes,1,opt,name=cancelled_qty,json=cancelledQty,proto3" json:"cancelled_qty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCancelOrderResponse) Reset()         { *m = MsgCancelOrderResponse{} }
func (m *MsgCancelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelOrderResponse) ProtoMessage()    {}
func (*MsgCancelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_648f734bf0b553a4, []int{3}
}
func (m *MsgCancelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCancelOrderResponse.Unmarshal(m, b)
}
func (m *MsgCancelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCancelOrderResponse.Marshal(b, m, deterministic)
}
func (m *MsgCancelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelOrderResponse.Merge(m, src)
}
func (m *MsgCancelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCancelOrderResponse.Size(m)
}
func (m *MsgCancelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelOrderResponse proto.InternalMessageInfo

func (m *MsgCancelOrderResponse) GetCancelledQty() string {
	if m != nil {
		return m.CancelledQty
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgPlaceOrder)(nil), "perpdex.orderbook.v1.MsgPlaceOrder")
	proto.RegisterType((*MsgPlaceOrderResponse)(nil), "perpdex.orderbook.v1.MsgPlaceOrderResponse")
	proto.RegisterType((*MsgCancelOrder)(nil), "perpdex.orderbook.v1.MsgCancelOrder")
	proto.RegisterType((*MsgCancelOrderResponse)(nil), "perpdex.orderbook.v1.MsgCancelOrderResponse")
}

func init() { proto.RegisterFile("perpdex/orderbook/v1/tx.proto", fileDescriptor_648f734bf0b553a4) }

var fileDescriptor_648f734bf0b553a4 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xfc, 0x23, 0x99, 0xd2, 0x4a, 0x58, 0x01, 0x5c, 0x57, 0x55, 0xa3, 0x94, 0x43,
	0x14, 0xa8, 0xb7, 0x49, 0x6f, 0x95, 0x40, 0xa2, 0x9c, 0x7a, 0x88, 0x68, 0xdd, 0x9e, 0x38, 0x10,
	0x6d, 0xbc, 0x8b, 0xbb, 0x6a, 0xec, 0x75, 0x77, 0xb7, 0x51, 0x7d, 0x43, 0x1c, 0xb9, 0xf0, 0x10,
	0xbc, 0x40, 0x90, 0x78, 0x0f, 0x24, 0x5e, 0x22, 0xaf, 0x81, 0xbc, 0xeb, 0x44, 0x0e, 0x18, 0xa9,
	0xea, 0x25, 0xca, 0xcc, 0x37, 0xb3, 0xfb, 0xcd, 0x6f, 0xbc, 0xb0, 0x9b, 0x50, 0x91, 0x10, 0x7a,
	0x87, 0xb8, 0x20, 0x54, 0x4c, 0x38, 0xbf, 0x46, 0xb3, 0x01, 0x52, 0x77, 0x5e, 0x22, 0xb8, 0xe2,
	0x76, 0x3b, 0x97, 0xbd, 0x95, 0xec, 0xcd, 0x06, 0x6e, 0xa7, 0xbc, 0x29, 0x4d, 0xa8, 0x34, 0x7d,
	0xee, 0xf3, 0x80, 0xcb, 0x88, 0x4b, 0x14, 0xc9, 0x30, 0x93, 0x22, 0x19, 0xe6, 0xc2, 0xb6, 0x11,
	0xc6, 0x3a, 0x42, 0x26, 0xc8, 0xa5, 0x27, 0x38, 0x62, 0x31, 0x47, 0xfa, 0xd7, 0xa4, 0xba, 0x3f,
	0x2a, 0xb0, 0x39, 0x92, 0xe1, 0xd9, 0x14, 0x07, 0xf4, 0x7d, 0x76, 0x97, 0x7d, 0x08, 0x0d, 0x25,
	0x30, 0xa1, 0xc2, 0xb1, 0x3a, 0x56, 0xaf, 0x75, 0xe2, 0xfc, 0xfe, 0x79, 0xd0, 0xce, 0x8f, 0x79,
	0x4b, 0x88, 0xa0, 0x52, 0x5e, 0x28, 0xc1, 0xe2, 0xd0, 0xcf, 0xeb, 0xec, 0x1d, 0x68, 0x45, 0x58,
	0x5c, 0x53, 0x35, 0x66, 0xc4, 0xa9, 0x64, 0x4d, 0x7e, 0xd3, 0x24, 0x4e, 0x89, 0xed, 0x41, 0x4d,
	0x32, 0x42, 0x9d, 0x6a, 0xc7, 0xea, 0x6d, 0x0d, 0x5d, 0xaf, 0x6c, 0x5c, 0xef, 0x82, 0x11, 0xea,
	0xeb, 0x3a, 0xfb, 0x0d, 0x80, 0x96, 0xc6, 0xd9, 0xb0, 0x4e, 0x4d, 0x77, 0xed, 0x95, 0x77, 0x69,
	0xbf, 0x97, 0x69, 0x42, 0xfd, 0x16, 0x5f, 0xfe, 0xb5, 0xdb, 0x50, 0x4f, 0x04, 0x0b, 0xa8, 0x53,
	0xd7, 0x46, 0x4c, 0x60, 0xbb, 0xd0, 0xbc, 0xb9, 0xc5, 0xb1, 0x62, 0x2a, 0x75, 0x1a, 0xc6, 0xe1,
	0x32, 0x3e, 0x46, 0x5f, 0x16, 0xf3, 0x7e, 0x3e, 0xcb, 0xd7, 0xc5, 0xbc, 0xbf, 0xf7, 0x2f, 0xfb,
	0x35, 0x42, 0xdd, 0xef, 0x16, 0x3c, 0x5d, 0xcb, 0xf8, 0x54, 0x26, 0x3c, 0x96, 0xd4, 0xde, 0x86,
	0xa6, 0x31, 0xcf, 0x88, 0xa1, 0xe7, 0x3f, 0xd2, 0xf1, 0x29, 0xb1, 0x77, 0x01, 0x3e, 0xb1, 0xe9,
	0x94, 0x92, 0xf1, 0x8d, 0x4a, 0x73, 0x4a, 0x2d, 0x93, 0x39, 0x57, 0x69, 0xc6, 0x10, 0xcf, 0xc2,
	0xb1, 0xb1, 0x5e, 0x35, 0x0e, 0xf1, 0x2c, 0x3c, 0xd3, 0xee, 0x8f, 0xf2, 0x95, 0x48, 0xa7, 0xd6,
	0xa9, 0xf6, 0x36, 0x86, 0x3b, 0xe5, 0x3c, 0x2e, 0xb3, 0x9a, 0x7c, 0x2b, 0xb2, 0xfb, 0xcd, 0x82,
	0xad, 0x91, 0x0c, 0xdf, 0xe1, 0x38, 0xa0, 0xd3, 0x87, 0xae, 0xb6, 0x38, 0x50, 0x65, 0x6d, 0xa0,
	0xe3, 0xc3, 0xbf, 0xb0, 0x75, 0x4a, 0xb1, 0x15, 0xae, 0xef, 0xbe, 0x86, 0x67, 0xeb, 0x99, 0x15,
	0xb7, 0x7d, 0xd8, 0x0c, 0x74, 0x7a, 0xc9, 0xc7, 0xc0, 0x7b, 0xbc, 0x4a, 0x9e, 0xab, 0x74, 0xf8,
	0xcb, 0x82, 0xea, 0x48, 0x86, 0xf6, 0x47, 0x80, 0xc2, 0xe7, 0xba, 0x5f, 0xce, 0x62, 0x6d, 0x3f,
	0xee, 0xcb, 0x7b, 0x14, 0xad, 0xcc, 0x60, 0xd8, 0x28, 0x42, 0x7b, 0xf1, 0xdf, 0xde, 0x42, 0x95,
	0xfb, 0xea, 0x3e, 0x55, 0xcb, 0x2b, 0xdc, 0xfa, 0xe7, 0xc5, 0xbc, 0x6f, 0x9d, 0x0c, 0x3e, 0xa0,
	0x90, 0xa9, 0xab, 0xdb, 0x89, 0x17, 0xf0, 0x08, 0xf1, 0x84, 0xc6, 0x78, 0x9a, 0x5c, 0x61, 0x94,
	0x1d, 0x75, 0x90, 0xa1, 0x2c, 0xc2, 0xd4, 0x8f, 0x7f, 0xd2, 0xd0, 0xcf, 0xf6, 0xe8, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x21, 0x37, 0x46, 0x51, 0x56, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// PlaceOrder places a new order
	PlaceOrder(ctx context.Context, in *MsgPlaceOrder, opts ...grpc.CallOption) (*MsgPlaceOrderResponse, error)
	// CancelOrder cancels an existing order
	CancelOrder(ctx context.Context, in *MsgCancelOrder, opts ...grpc.CallOption) (*MsgCancelOrderResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) PlaceOrder(ctx context.Context, in *MsgPlaceOrder, opts ...grpc.CallOption) (*MsgPlaceOrderResponse, error) {
	out := new(MsgPlaceOrderResponse)
	err := c.cc.Invoke(ctx, "/perpdex.orderbook.v1.Msg/PlaceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelOrder(ctx context.Context, in *MsgCancelOrder, opts ...grpc.CallOption) (*MsgCancelOrderResponse, error) {
	out := new(MsgCancelOrderResponse)
	err := c.cc.Invoke(ctx, "/perpdex.orderbook.v1.Msg/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// PlaceOrder places a new order
	PlaceOrder(context.Context, *MsgPlaceOrder) (*MsgPlaceOrderResponse, error)
	// CancelOrder cancels an existing order
	CancelOrder(context.Context, *MsgCancelOrder) (*MsgCancelOrderResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) PlaceOrder(ctx context.Context, req *MsgPlaceOrder) (*MsgPlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (*UnimplementedMsgServer) CancelOrder(ctx context.Context, req *MsgCancelOrder) (*MsgCancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPlaceOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.orderbook.v1.Msg/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PlaceOrder(ctx, req.(*MsgPlaceOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/perpdex.orderbook.v1.Msg/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelOrder(ctx, req.(*MsgCancelOrder))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "perpdex.orderbook.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _Msg_PlaceOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Msg_CancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perpdex/orderbook/v1/tx.proto",
}
