// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perpdex/orderbook/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Side represents the order side
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

var Side_name = map[int32]string{
	0: "SIDE_UNSPECIFIED",
	1: "SIDE_BUY",
	2: "SIDE_SELL",
}

var Side_value = map[string]int32{
	"SIDE_UNSPECIFIED": 0,
	"SIDE_BUY":         1,
	"SIDE_SELL":        2,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{0}
}

// OrderType represents the type of order
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "ORDER_TYPE_UNSPECIFIED",
	1: "ORDER_TYPE_LIMIT",
	2: "ORDER_TYPE_MARKET",
}

var OrderType_value = map[string]int32{
	"ORDER_TYPE_UNSPECIFIED": 0,
	"ORDER_TYPE_LIMIT":       1,
	"ORDER_TYPE_MARKET":      2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{1}
}

// OrderStatus represents the current status of an order
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_OPEN             OrderStatus = 1
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 2
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 4
)

var OrderStatus_name = map[int32]string{
	0: "ORDER_STATUS_UNSPECIFIED",
	1: "ORDER_STATUS_OPEN",
	2: "ORDER_STATUS_FILLED",
	3: "ORDER_STATUS_PARTIALLY_FILLED",
	4: "ORDER_STATUS_CANCELLED",
}

var OrderStatus_value = map[string]int32{
	"ORDER_STATUS_UNSPECIFIED":      0,
	"ORDER_STATUS_OPEN":             1,
	"ORDER_STATUS_FILLED":           2,
	"ORDER_STATUS_PARTIALLY_FILLED": 3,
	"ORDER_STATUS_CANCELLED":        4,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{2}
}

// Order represents a trading order
type Order struct {
	OrderId              string      `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Trader               string      `protobuf:"bytes,2,opt,name=trader,proto3" json:"trader,omitempty"`
	MarketId             string      `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side                 Side        `protobuf:"varint,4,opt,name=side,proto3,enum=perpdex.orderbook.v1.Side" json:"side,omitempty"`
	OrderType            OrderType   `protobuf:"varint,5,opt,name=order_type,json=orderType,proto3,enum=perpdex.orderbook.v1.OrderType" json:"order_type,omitempty"`
	Price                string      `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string      `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	FilledQty            string      `protobuf:"bytes,8,opt,name=filled_qty,json=filledQty,proto3" json:"filled_qty,omitempty"`
	Status               OrderStatus `protobuf:"varint,9,opt,name=status,proto3,enum=perpdex.orderbook.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt            int64       `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64       `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *Order) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *Order) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *Order) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Order) GetFilledQty() string {
	if m != nil {
		return m.FilledQty
	}
	return ""
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Order) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// PriceLevel represents orders at a specific price
type PriceLevel struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string   `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderIds             []string `protobuf:"bytes,3,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceLevel) Reset()         { *m = PriceLevel{} }
func (m *PriceLevel) String() string { return proto.CompactTextString(m) }
func (*PriceLevel) ProtoMessage()    {}
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{1}
}
func (m *PriceLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceLevel.Unmarshal(m, b)
}
func (m *PriceLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceLevel.Marshal(b, m, deterministic)
}
func (m *PriceLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceLevel.Merge(m, src)
}
func (m *PriceLevel) XXX_Size() int {
	return xxx_messageInfo_PriceLevel.Size(m)
}
func (m *PriceLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceLevel.DiscardUnknown(m)
}

var xxx_messageInfo_PriceLevel proto.InternalMessageInfo

func (m *PriceLevel) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PriceLevel) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *PriceLevel) GetOrderIds() []string {
	if m != nil {
		return m.OrderIds
	}
	return nil
}

// OrderBook represents the order book for a market
type OrderBook struct {
	MarketId             string        `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Bids                 []*PriceLevel `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks                 []*PriceLevel `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderBook) Reset()         { *m = OrderBook{} }
func (m *OrderBook) String() string { return proto.CompactTextString(m) }
func (*OrderBook) ProtoMessage()    {}
func (*OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{2}
}
func (m *OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBook.Unmarshal(m, b)
}
func (m *OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBook.Marshal(b, m, deterministic)
}
func (m *OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBook.Merge(m, src)
}
func (m *OrderBook) XXX_Size() int {
	return xxx_messageInfo_OrderBook.Size(m)
}
func (m *OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBook proto.InternalMessageInfo

func (m *OrderBook) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *OrderBook) GetBids() []*PriceLevel {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *OrderBook) GetAsks() []*PriceLevel {
	if m != nil {
		return m.Asks
	}
	return nil
}

// Trade represents an executed trade
type Trade struct {
	TradeId              string   `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	TakerOrderId         string   `protobuf:"bytes,3,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerOrderId         string   `protobuf:"bytes,4,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	Taker                string   `protobuf:"bytes,5,opt,name=taker,proto3" json:"taker,omitempty"`
	Maker                string   `protobuf:"bytes,6,opt,name=maker,proto3" json:"maker,omitempty"`
	TakerSide            Side     `protobuf:"varint,7,opt,name=taker_side,json=takerSide,proto3,enum=perpdex.orderbook.v1.Side" json:"taker_side,omitempty"`
	Price                string   `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             string   `protobuf:"bytes,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TakerFee             string   `protobuf:"bytes,10,opt,name=taker_fee,json=takerFee,proto3" json:"taker_fee,omitempty"`
	MakerFee             string   `protobuf:"bytes,11,opt,name=maker_fee,json=makerFee,proto3" json:"maker_fee,omitempty"`
	Timestamp            int64    `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{3}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *Trade) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *Trade) GetTakerOrderId() string {
	if m != nil {
		return m.TakerOrderId
	}
	return ""
}

func (m *Trade) GetMakerOrderId() string {
	if m != nil {
		return m.MakerOrderId
	}
	return ""
}

func (m *Trade) GetTaker() string {
	if m != nil {
		return m.Taker
	}
	return ""
}

func (m *Trade) GetMaker() string {
	if m != nil {
		return m.Maker
	}
	return ""
}

func (m *Trade) GetTakerSide() Side {
	if m != nil {
		return m.TakerSide
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *Trade) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Trade) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Trade) GetTakerFee() string {
	if m != nil {
		return m.TakerFee
	}
	return ""
}

func (m *Trade) GetMakerFee() string {
	if m != nil {
		return m.MakerFee
	}
	return ""
}

func (m *Trade) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// GenesisState defines the orderbook module's genesis state
type GenesisState struct {
	Orders               []*Order     `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	OrderBooks           []*OrderBook `protobuf:"bytes,2,rep,name=order_books,json=orderBooks,proto3" json:"order_books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a41d1f099ed9b27, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *GenesisState) GetOrderBooks() []*OrderBook {
	if m != nil {
		return m.OrderBooks
	}
	return nil
}

func init() {
	proto.RegisterEnum("perpdex.orderbook.v1.Side", Side_name, Side_value)
	proto.RegisterEnum("perpdex.orderbook.v1.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("perpdex.orderbook.v1.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterType((*Order)(nil), "perpdex.orderbook.v1.Order")
	proto.RegisterType((*PriceLevel)(nil), "perpdex.orderbook.v1.PriceLevel")
	proto.RegisterType((*OrderBook)(nil), "perpdex.orderbook.v1.OrderBook")
	proto.RegisterType((*Trade)(nil), "perpdex.orderbook.v1.Trade")
	proto.RegisterType((*GenesisState)(nil), "perpdex.orderbook.v1.GenesisState")
}

func init() { proto.RegisterFile("perpdex/orderbook/v1/types.proto", fileDescriptor_0a41d1f099ed9b27) }

var fileDescriptor_0a41d1f099ed9b27 = []byte{
	// 735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0xce, 0xa3, 0xf1, 0x4d, 0xa8, 0xcc, 0x10, 0x8a, 0xe9, 0x43, 0xa4, 0x51, 0x17, 0x51,
	0x25, 0x12, 0xb5, 0x65, 0xd3, 0x0d, 0x22, 0x6d, 0x5c, 0x64, 0xe1, 0x36, 0x61, 0xe2, 0x2e, 0x0a,
	0x8b, 0xc8, 0xa9, 0xa7, 0xd4, 0x4a, 0x52, 0xbb, 0xf6, 0xa4, 0x22, 0x1f, 0xc0, 0x07, 0x20, 0xb1,
	0xe2, 0x5b, 0x59, 0xa0, 0xb9, 0x63, 0xe7, 0x45, 0x5b, 0xd8, 0xe5, 0x9e, 0x73, 0xee, 0xcc, 0x99,
	0xb9, 0xc7, 0x19, 0xa8, 0x84, 0x2c, 0x0a, 0x3d, 0xf6, 0xad, 0x11, 0x44, 0x1e, 0x8b, 0xfa, 0x41,
	0x30, 0x68, 0xdc, 0xed, 0x35, 0xf8, 0x24, 0x64, 0x71, 0x3d, 0x8c, 0x02, 0x1e, 0x90, 0x72, 0xa2,
	0xa8, 0x4f, 0x15, 0xf5, 0xbb, 0xbd, 0xea, 0x8f, 0x0c, 0xe4, 0xda, 0x02, 0x20, 0xaf, 0xa0, 0x80,
	0x4c, 0xcf, 0xf7, 0x0c, 0xa5, 0xa2, 0xd4, 0x34, 0xba, 0x82, 0xb5, 0xe5, 0x91, 0x35, 0xc8, 0xf3,
	0xc8, 0xf5, 0x58, 0x64, 0xa8, 0x48, 0x24, 0x15, 0xd9, 0x00, 0x6d, 0xe4, 0x46, 0x03, 0xc6, 0x45,
	0x4f, 0x06, 0xa9, 0x82, 0x04, 0x2c, 0x8f, 0xd4, 0x21, 0x1b, 0xfb, 0x1e, 0x33, 0xb2, 0x15, 0xa5,
	0xb6, 0xba, 0xbf, 0x5e, 0xbf, 0x6f, 0xfb, 0x7a, 0xd7, 0xf7, 0x18, 0x45, 0x1d, 0x79, 0x07, 0x20,
	0xf7, 0x17, 0xa6, 0x8d, 0x1c, 0x76, 0xbd, 0xbe, 0xbf, 0x0b, 0x0d, 0x3b, 0x93, 0x90, 0x51, 0x2d,
	0x48, 0x7f, 0x92, 0x32, 0xe4, 0xc2, 0xc8, 0xbf, 0x64, 0x46, 0x1e, 0x8d, 0xc8, 0x82, 0xac, 0x43,
	0xe1, 0x76, 0xec, 0xde, 0x70, 0x9f, 0x4f, 0x8c, 0x15, 0xe9, 0x30, 0xad, 0xc9, 0x16, 0xc0, 0x95,
	0x3f, 0x1c, 0x32, 0xaf, 0x77, 0xcb, 0x27, 0x46, 0x01, 0x59, 0x4d, 0x22, 0x9f, 0xf8, 0x84, 0x1c,
	0x42, 0x3e, 0xe6, 0x2e, 0x1f, 0xc7, 0x86, 0x86, 0x66, 0xb6, 0x1f, 0x31, 0xd3, 0x45, 0x21, 0x4d,
	0x1a, 0xc4, 0xca, 0x97, 0x11, 0x73, 0x39, 0xf3, 0x7a, 0x2e, 0x37, 0xa0, 0xa2, 0xd4, 0x32, 0x54,
	0x4b, 0x90, 0x26, 0x17, 0xf4, 0x38, 0xf4, 0x52, 0xba, 0x28, 0xe9, 0x04, 0x69, 0xf2, 0xea, 0x17,
	0x80, 0x8e, 0x30, 0x6f, 0xb3, 0x3b, 0x36, 0x9c, 0x9d, 0x4b, 0x79, 0xe8, 0x5c, 0xea, 0xd2, 0xb9,
	0x36, 0x40, 0x4b, 0x27, 0x19, 0x1b, 0x99, 0x4a, 0x46, 0x90, 0xc9, 0x28, 0xe3, 0xea, 0x4f, 0x05,
	0x34, 0xb4, 0x7c, 0x14, 0x04, 0x83, 0xc5, 0x09, 0x2a, 0x4b, 0x13, 0x7c, 0x0b, 0xd9, 0xbe, 0x58,
	0x42, 0xad, 0x64, 0x6a, 0xc5, 0xfd, 0xca, 0xfd, 0xc7, 0x9f, 0x39, 0xa5, 0xa8, 0x16, 0x5d, 0x6e,
	0x3c, 0x90, 0x1b, 0xff, 0x57, 0x97, 0x50, 0x57, 0x7f, 0xab, 0x90, 0x73, 0x44, 0xaa, 0x44, 0x0e,
	0x31, 0x5e, 0x73, 0x39, 0xc4, 0xda, 0xf2, 0x16, 0xdd, 0xaa, 0x4b, 0x6e, 0x77, 0x60, 0x95, 0xbb,
	0x03, 0x16, 0xf5, 0xa6, 0x29, 0x96, 0x89, 0x2c, 0x21, 0xda, 0x4e, 0xa2, 0xbc, 0x03, 0xab, 0xa3,
	0x45, 0x55, 0x56, 0xaa, 0x46, 0xf3, 0xaa, 0x32, 0xe4, 0xb0, 0x0b, 0x63, 0xa8, 0x51, 0x59, 0x08,
	0x14, 0x55, 0x69, 0xc2, 0xb0, 0x20, 0x87, 0x00, 0x72, 0x5f, 0x4c, 0xfb, 0xca, 0x3f, 0xd3, 0xae,
	0xa1, 0x5a, 0xfc, 0x9c, 0x8d, 0xb6, 0xf0, 0xd0, 0x68, 0xb5, 0xbf, 0x47, 0x2b, 0x37, 0xbb, 0x62,
	0x0c, 0x73, 0xa5, 0xd1, 0x02, 0x02, 0x27, 0x8c, 0xc9, 0xeb, 0x49, 0xc9, 0x62, 0x7a, 0x3d, 0x09,
	0xb9, 0x09, 0x1a, 0xf7, 0x47, 0x2c, 0xe6, 0xee, 0x28, 0x34, 0x4a, 0x32, 0x72, 0x53, 0xa0, 0xfa,
	0x5d, 0x81, 0xd2, 0x07, 0x76, 0xc3, 0x62, 0x3f, 0x16, 0x51, 0x66, 0xe4, 0x00, 0xf2, 0x68, 0x3d,
	0x36, 0x14, 0x9c, 0xe3, 0xc6, 0x23, 0xe1, 0xa7, 0x89, 0x94, 0xbc, 0x87, 0xa2, 0xbc, 0x56, 0x41,
	0xa7, 0xb9, 0x79, 0xec, 0x1b, 0x16, 0x19, 0xa4, 0xf2, 0xb3, 0x17, 0x3f, 0xe3, 0xdd, 0x43, 0xc8,
	0x26, 0x37, 0xa3, 0x77, 0xad, 0x96, 0xd9, 0x3b, 0x3f, 0xeb, 0x76, 0xcc, 0x63, 0xeb, 0xc4, 0x32,
	0x5b, 0xfa, 0x13, 0x52, 0x82, 0x02, 0xa2, 0x47, 0xe7, 0x17, 0xba, 0x42, 0x9e, 0x82, 0x86, 0x55,
	0xd7, 0xb4, 0x6d, 0x5d, 0xdd, 0x75, 0x92, 0x5c, 0xe3, 0x9f, 0xc1, 0x3a, 0xac, 0xb5, 0x69, 0xcb,
	0xa4, 0x3d, 0xe7, 0xa2, 0xb3, 0xbc, 0x4a, 0x19, 0xf4, 0x39, 0xce, 0xb6, 0x4e, 0x2d, 0x47, 0x57,
	0xc8, 0x0b, 0x78, 0x36, 0x87, 0x9e, 0x36, 0xe9, 0x47, 0xd3, 0xd1, 0xd5, 0xdd, 0x5f, 0x0a, 0x14,
	0xe7, 0xbe, 0x70, 0xb2, 0x09, 0x86, 0x94, 0x75, 0x9d, 0xa6, 0x73, 0xde, 0x5d, 0x5a, 0x7a, 0xba,
	0x48, 0xc2, 0xb6, 0x3b, 0xe6, 0x99, 0xae, 0x90, 0x97, 0xf0, 0x7c, 0x01, 0x3e, 0xb1, 0x6c, 0xdb,
	0x6c, 0xe9, 0x2a, 0xd9, 0x86, 0xad, 0x05, 0xa2, 0xd3, 0xa4, 0x8e, 0xd5, 0xb4, 0xed, 0x8b, 0x54,
	0x92, 0x99, 0x9d, 0x24, 0x91, 0x1c, 0x37, 0xcf, 0x8e, 0x4d, 0xe4, 0xb2, 0x47, 0x7b, 0x9f, 0x1b,
	0x5f, 0x7d, 0x7e, 0x3d, 0xee, 0xd7, 0x2f, 0x83, 0x51, 0x23, 0x08, 0xd9, 0x8d, 0x3b, 0x0c, 0xaf,
	0xdd, 0x86, 0xb8, 0xf0, 0x37, 0xe2, 0x31, 0x98, 0x7f, 0x0e, 0xf0, 0x2d, 0xe8, 0xe7, 0xf1, 0x31,
	0x38, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x11, 0xb2, 0x55, 0x23, 0x30, 0x06, 0x00, 0x00,
}
